import { Audio, Video } from "@remotion/media";
import { AbsoluteFill, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import type { SolomonCreatorStoryV9Manifest, V9Caption, V9Scene, V9Source } from "../../shared/solomonCreatorStoryV9";
import { RobotMascotV9 } from "../mascotV9/RobotMascotV9";

const INK="#07111f", PAPER="#fbf8f0", WHITE="#fff", MINT="#39f2b5", GREEN="#087052", CORAL="#ff6f61", AMBER="#ff9d18";
const FILES={jobs:"proof-jobs.mp4",tracker:"proof-tracker.mp4",contacts:"proof-contacts.mp4",outreach:"proof-outreach.mp4"} as const;

export const SolomonCreatorStoryV9:React.FC<SolomonCreatorStoryV9Manifest> = (manifest) => <AbsoluteFill style={{background:INK,color:INK,fontFamily:"Manrope Variable,Manrope,sans-serif",overflow:"hidden"}}>
  {manifest.scenes.map(scene=><Sequence key={scene.id} from={scene.from} durationInFrames={scene.to-scene.from} premountFor={30} name={scene.id}><Scene scene={scene} sources={manifest.sources}/></Sequence>)}
  {manifest.captions.map(caption=><Sequence key={caption.id} from={caption.from} durationInFrames={caption.to-caption.from} premountFor={10}><Caption caption={caption}/></Sequence>)}
  <Audio src={staticFile("narration.wav")}/><Audio src={staticFile("sound-design.wav")}/>
</AbsoluteFill>;

const Scene:React.FC<{scene:V9Scene;sources:V9Source[]}> = ({scene,sources}) => {
  const source=scene.assetId?sources.find(item=>item.id===scene.assetId):undefined;
  if(scene.family==="mascot_hook"||scene.family==="friction")return <Host scene={scene}/>;
  if(scene.family==="five_surfaces")return <FiveSurfaces scene={scene}/>;
  if(scene.family==="signature")return <Signature scene={scene} source={source!}/>;
  if(scene.family==="payoff")return <Payoff scene={scene} sources={sources}/>;
  if(scene.family==="cta"||scene.family==="sting")return <Cta scene={scene}/>;
  return <ProductScene scene={scene} source={source!}/>;
};

const Host:React.FC<{scene:V9Scene}> = ({scene}) => {const frame=useCurrentFrame(),friction=scene.family==="friction";return <AbsoluteFill style={{background:friction?"radial-gradient(circle at 50% 32%,#fff5ef,#ffdcd5)":"radial-gradient(circle at 50% 28%,#e9fff7,#caeee3 52%,#9ed8ca)"}}>{friction&&<div style={{position:"absolute",left:58,right:58,top:98,fontFamily:"Fraunces Variable,serif",fontSize:72,lineHeight:.96,fontWeight:780,textAlign:"center"}}>THE OLD WAY<br/><i style={{color:CORAL}}>LOSES CONTEXT.</i></div>}{friction&&[0,1,2].map(index=><div key={index} style={{position:"absolute",left:80+index*270,top:500+index*85,width:350,height:240,background:WHITE,borderRadius:28,border:"2px solid #e5bdb4",boxShadow:"0 24px 55px rgba(109,42,31,.18)",transform:`translateX(${interpolate(frame,[0,8+index*3],[index%2?-400:400,0],{extrapolateRight:"clamp"})}px) rotate(${index*4-4}deg)`}}><div style={{height:40,background:"#ffe9e4",borderRadius:"26px 26px 0 0"}}/><div style={{padding:25,fontWeight:900,color:CORAL}}>ANOTHER TAB</div></div>)}<RobotMascotV9 plan={scene.mascot}/></AbsoluteFill>;};

const ProductScene:React.FC<{scene:V9Scene;source:V9Source}> = ({scene,source}) => {const frame=useCurrentFrame(), status=scene.family==="status_action",contact=scene.family==="contact_reveal"||scene.family==="reason_steps",draft=["draft_build","comparison","human_control"].includes(scene.family);return <AbsoluteFill style={{background:scene.family==="comparison"?"linear-gradient(145deg,#fff4ee,#eafff8)":PAPER}}><div style={{position:"absolute",left:55,right:55,top:290,height:draft?1010:contact?1040:980}}><Proof source={source} scene={scene}/></div>{status&&<><StatusBadge frame={frame}/><CursorArrow frame={frame} from={{x:900,y:1180}} to={{x:770,y:880}} clickAt={12}/></>} {contact&&<EvidenceChips frame={frame} detailed={scene.family==="reason_steps"}/>} {scene.family==="role_object"&&<div style={{position:"absolute",left:410,right:55,top:1320,display:"grid",gap:12}}><ProofChip text="PRODUCT ENGINEER" primary/><ProofChip text="NORTHSTAR LABS"/></div>} {draft&&<DraftOverlay frame={frame} family={scene.family}/>} {scene.family==="human_control"&&<CursorArrow frame={frame} from={{x:920,y:1120}} to={{x:735,y:820}} clickAt={16}/>}<RobotMascotV9 plan={scene.mascot}/></AbsoluteFill>;};

const Proof:React.FC<{source:V9Source;scene:V9Scene}> = ({source,scene}) => {const frame=useCurrentFrame(),focus=scene.productFocus!,motion=Math.sin(frame/9)*.032,focusMotion=Math.sin(frame/13)*.018,zoom=focus.zoom+motion,box={left:0,top:0,width:970,height:scene.family==="contact_reveal"||scene.family==="reason_steps"?1040:980};const sourceW=box.height*source.sourceWidth/source.sourceHeight,left=clamp(box.width/2-(focus.x+focusMotion)*sourceW*zoom,box.width-sourceW*zoom,0),top=clamp(box.height/2-(focus.y-focusMotion*.5)*box.height*zoom,box.height-box.height*zoom,0);return <div data-clean-product={scene.id} style={{position:"absolute",...box,overflow:"hidden",borderRadius:32,background:WHITE,border:"2px solid rgba(7,17,31,.12)",boxShadow:"0 28px 70px rgba(7,17,31,.18)"}}><div style={{position:"absolute",left,top,width:sourceW,height:box.height,transform:`scale(${zoom})`,transformOrigin:"0 0"}}><Video src={staticFile(FILES[source.id])} trimBefore={Math.round(focus.trim*30)} muted style={{width:"100%",height:"100%"}}/></div></div>;};

const StatusBadge:React.FC<{frame:number}> = ({frame}) => {const p=spring({frame:Math.max(0,frame-7),fps:30,config:{damping:13,stiffness:190}});return <div style={{position:"absolute",left:220,right:220,top:730,padding:"25px 30px",background:WHITE,border:`5px solid ${GREEN}`,borderRadius:28,textAlign:"center",boxShadow:"0 25px 70px rgba(7,112,82,.25)",transform:`scale(${.7+.3*p})`}}><div style={{fontSize:25,fontWeight:900,color:GREEN}}>MOVED TO</div><div style={{fontFamily:"Fraunces Variable,serif",fontSize:75,fontWeight:900}}>INTERVIEWING</div></div>;};
const EvidenceChips:React.FC<{frame:number;detailed:boolean}> = ({frame,detailed}) => <div style={{position:"absolute",left:430,right:55,top:1350,display:"grid",gap:12}}>{(detailed?["AT THE TARGET COMPANY","RELEVANT TO HIRING","SYNTHETIC PROOF ATTACHED"]:["AVERY CHEN","SENIOR TECHNICAL RECRUITER","NORTHSTAR LABS"]).map((label,index)=><div key={label} style={{padding:"14px 20px",borderRadius:16,background:index===0?INK:WHITE,color:index===0?WHITE:INK,border:`2px solid ${index===0?INK:"#c9d8d1"}`,fontSize:25,fontWeight:900,opacity:interpolate(frame,[index*6,index*6+8],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),transform:`translateX(${interpolate(frame,[index*6,index*6+8],[50,0],{extrapolateRight:"clamp"})}px)`}}>{label}</div>)}</div>;
const ProofChip:React.FC<{text:string;primary?:boolean}> = ({text,primary}) => <div style={{padding:"14px 20px",borderRadius:16,background:primary?INK:WHITE,color:primary?WHITE:INK,border:`2px solid ${primary?INK:"#c9d8d1"}`,fontSize:27,fontWeight:950}}>{text}</div>;
const DraftOverlay:React.FC<{frame:number;family:V9Scene["family"]}> = ({frame,family}) => {if(family==="human_control")return <div style={{position:"absolute",left:390,right:55,top:1240,padding:"17px 20px",background:WHITE,border:`4px solid ${GREEN}`,borderRadius:22,fontWeight:950,textAlign:"center"}}><div style={{fontSize:28}}>SAVE EDIT &nbsp;·&nbsp; CANCEL</div><div style={{fontSize:21,color:GREEN,marginTop:5}}>YOU REVIEW AND SEND MANUALLY</div></div>;const items=family==="comparison"?["GENERIC OPENER","ROLE + COMPANY CONTEXT"]:["ROLE","COMPANY","WHY AVERY","CLEAR ASK"];return <div style={{position:"absolute",left:family==="comparison"?315:335,right:65,top:1310,display:"flex",gap:10,flexWrap:"wrap"}}>{items.map((label,index)=><span key={label} style={{padding:"12px 17px",borderRadius:999,background:index===items.length-1?MINT:INK,color:index===items.length-1?INK:WHITE,fontSize:22,fontWeight:900,opacity:interpolate(frame,[index*7,index*7+8],[0,1],{extrapolateRight:"clamp"})}}>{label}</span>)}</div>;};

const FiveSurfaces:React.FC<{scene:V9Scene}> = ({scene}) => {const frame=useCurrentFrame(),labels=["JOB POST","PROFILE","NOTES","CONTACTS","BLANK EMAIL"],collapse=interpolate(frame,[65,95],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <AbsoluteFill style={{background:"linear-gradient(145deg,#fff6ef,#ffe5dd)"}}><div style={{position:"absolute",left:55,right:55,top:100,fontFamily:"Fraunces Variable,serif",fontSize:72,fontWeight:800}}>FIVE SURFACES.<br/><i style={{color:CORAL}}>SAME CONTEXT.</i></div>{labels.map((label,index)=>{const x=55+(index%2)*460,y=380+Math.floor(index/2)*260,enter=spring({frame:Math.max(0,frame-index*7),fps:30,config:{damping:15,stiffness:165},durationInFrames:16});return <div key={label} style={{position:"absolute",left:x+(520-x)*collapse,top:y+(920-y)*collapse,width:410,height:210,padding:28,borderRadius:27,background:WHITE,border:"2px solid #efc7bf",boxShadow:"0 20px 50px rgba(103,44,32,.14)",opacity:enter*(1-collapse*.82),transform:`scale(${.8+.2*enter-.6*collapse}) rotate(${index%2?-3:3}deg)`}}><div style={{fontSize:25,fontWeight:950,color:CORAL}}>{index+1}/5</div><div style={{fontSize:34,fontWeight:950,marginTop:22}}>{label}</div><div style={{height:10,width:`${52+index*8}%`,background:"#f2e5e1",borderRadius:6,marginTop:22}}/></div>})}<div style={{position:"absolute",left:390,top:790,padding:"28px 44px",background:INK,color:WHITE,borderRadius:28,fontSize:36,fontWeight:950,opacity:collapse,transform:`scale(${.65+.35*collapse})`}}>ONE OPPORTUNITY</div><RobotMascotV9 plan={scene.mascot}/></AbsoluteFill>;};

const Signature:React.FC<{scene:V9Scene;source:V9Source}> = ({scene,source}) => {const frame=useCurrentFrame(),tokens=[{label:"JOB",x:90},{label:"PERSON",x:310},{label:"PROOF",x:580},{label:"MESSAGE",x:810}];return <AbsoluteFill style={{background:"linear-gradient(145deg,#e8fff7,#d9eef8)"}}><div style={{position:"absolute",left:54,right:54,top:300,height:820}}><Proof source={source} scene={scene}/></div><svg width="1080" height="1920" style={{position:"absolute",inset:0}}><path d="M150 1325 C330 1180 745 1180 930 1325" fill="none" stroke={GREEN} strokeWidth="10" strokeLinecap="round" strokeDasharray="18 18"/></svg>{tokens.map((token,index)=>{const p=spring({frame:Math.max(0,frame-index*18),fps:30,config:{damping:15,stiffness:170},durationInFrames:18});return <div key={token.label} style={{position:"absolute",left:token.x,top:1280,width:180,padding:"20px 8px",textAlign:"center",borderRadius:999,background:index===3?MINT:INK,color:index===3?INK:WHITE,fontSize:26,fontWeight:950,transform:`translateY(${(1-p)*80}px) scale(${.7+.3*p})`,opacity:p}}>{token.label}</div>})}<div style={{position:"absolute",left:330,right:330,top:1470,textAlign:"center",fontSize:24,fontWeight:850,color:GREEN}}>CONCEPTUAL CONNECTION · VERIFIED PRODUCT PROOF</div><RobotMascotV9 plan={scene.mascot}/></AbsoluteFill>;};

const Payoff:React.FC<{scene:V9Scene;sources:V9Source[]}> = ({scene,sources}) => {const frame=useCurrentFrame(),ready=frame>=21,active=Math.min(3,Math.max(0,Math.floor((frame-21)/36))),items=[{label:"INTERVIEWING",asset:"tracker",position:"50% 48%"},{label:"AVERY CHEN",asset:"contacts",position:"18% 70%"},{label:"PROOF ATTACHED",asset:"contacts",position:"20% 78%"},{label:"EDITABLE MESSAGE",asset:"outreach",position:"64% 74%"}] as const,item=items[active]??items[0],source=sources.find(({id})=>id===item.asset)!;const enter=spring({frame:Math.max(0,frame-21-active*36),fps:30,config:{damping:15,stiffness:175},durationInFrames:16});return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 35%,#ddfff3,#acdccc)"}}><div style={{position:"absolute",left:70,right:70,top:245,height:850,overflow:"hidden",borderRadius:34,background:WHITE,border:`6px solid ${GREEN}`,boxShadow:"0 30px 70px rgba(7,17,31,.2)",opacity:ready?1:0,transform:`scale(${.9+.1*enter})`}}><Video key={`${item.label}-${active}`} src={staticFile(FILES[source.id])} trimBefore={item.asset==="outreach"?42:36} muted objectFit="cover" style={{width:"100%",height:"100%",objectPosition:item.position,transform:`scale(${item.asset==="tracker"?1.18:1.32})`}}/><div style={{position:"absolute",left:18,bottom:18,padding:"12px 18px",borderRadius:14,background:item.asset==="outreach"?MINT:INK,color:item.asset==="outreach"?INK:WHITE,fontSize:28,fontWeight:950}}>{item.label}</div></div><div style={{position:"absolute",left:70,right:70,top:1120,display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{items.map((entry,index)=><div key={entry.label} style={{padding:"13px 8px",borderRadius:13,textAlign:"center",background:index<=active?(index===3?MINT:INK):"rgba(255,255,255,.68)",color:index<=active?(index===3?INK:WHITE):INK,border:"2px solid rgba(7,17,31,.12)",fontSize:20,fontWeight:950}}>{index<=active?"✓ ":""}{entry.label}</div>)}</div><div style={{position:"absolute",left:120,right:120,top:1285,padding:"18px",background:INK,color:WHITE,textAlign:"center",borderRadius:22,fontFamily:"Fraunces Variable,serif",fontSize:42,fontWeight:850}}>ONE CONNECTED NEXT STEP.</div>{frame>=150&&<RobotMascotV9 plan={scene.mascot}/>}</AbsoluteFill>;};

const Cta:React.FC<{scene:V9Scene}> = ({scene}) => {const frame=useCurrentFrame(),sting=scene.family==="sting",pulse=1+Math.sin(frame/5)*.025;return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 34%,#e8fff7,#b9e5d8)"}}>{!sting&&<div style={{position:"absolute",left:700,top:1230,width:165,height:165,background:INK,borderRadius:46,transform:`scale(${pulse})`,boxShadow:"0 20px 50px rgba(7,17,31,.25)",display:"grid",placeItems:"center"}}><svg viewBox="0 0 80 96" width="78" height="94"><path d="M14 8 H66 V84 L40 68 L14 84 Z" fill="none" stroke={MINT} strokeWidth="10" strokeLinejoin="round"/></svg></div>}{sting&&<div style={{position:"absolute",inset:0,display:"grid",placeItems:"center"}}><div style={{fontFamily:"Fraunces Variable,serif",fontSize:112,fontWeight:900,color:GREEN}}>SOLOMON<span style={{color:AMBER}}>.</span></div></div>}<RobotMascotV9 plan={scene.mascot}/></AbsoluteFill>;};

const Caption:React.FC<{caption:V9Caption}> = ({caption}) => {const frame=useCurrentFrame(),{durationInFrames}=useVideoConfig(),enter=spring({frame,fps:30,config:{damping:16,stiffness:175},durationInFrames:10}),opacity=interpolate(frame,[Math.max(0,durationInFrames-4),durationInFrames],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),parts=caption.highlight?caption.text.split(caption.highlight):[caption.text];return <div data-v9-caption={caption.id} style={{position:"absolute",left:45,right:45,[caption.zone==="top"?"top":"bottom"]:caption.zone==="top"?100:100,display:"flex",justifyContent:"center",zIndex:50,opacity,transform:`translateY(${(1-enter)*(caption.zone==="top"?-30:30)}px)`}}><div style={{padding:"13px 20px",borderRadius:15,background:"rgba(7,17,31,.9)",color:WHITE,fontSize:caption.id==="hook"?40:caption.id==="cta"?38:43,lineHeight:1.05,textAlign:"center",fontWeight:950,boxShadow:"0 12px 30px rgba(0,0,0,.18)"}}>{parts[0]}{caption.highlight&&<span style={{color:MINT}}>{caption.highlight}</span>}{parts[1]}</div></div>;};
const CursorArrow:React.FC<{frame:number;from:{x:number;y:number};to:{x:number;y:number};clickAt:number}> = ({frame,from,to,clickAt}) => {const p=interpolate(frame,[0,Math.max(1,clickAt-2)],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),click=interpolate(frame,[clickAt-1,clickAt,clickAt+3],[1,.82,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <svg viewBox="0 0 40 52" width="52" height="68" style={{position:"absolute",left:from.x+(to.x-from.x)*p,top:from.y+(to.y-from.y)*p,zIndex:45,transform:`scale(${click})`,filter:"drop-shadow(0 4px 4px rgba(0,0,0,.4))"}}><path d="M4 3 L4 39 L14 30 L22 48 L30 44 L22 27 L36 27 Z" fill="#fff" stroke="#111827" strokeWidth="3"/></svg>;};
function clamp(value:number,min:number,max:number){return Math.max(min,Math.min(max,value));}
