import type { CSSProperties } from "react";
import { Audio, Video } from "@remotion/media";
import { AbsoluteFill, interpolate, Sequence, spring, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import { sampleIrregularIdle, sampleSpeechEnvelope, type RobotDirection } from "../../shared/gideonRobotV7";
import type { SolomonCreatorStoryV7Manifest, V7Caption, V7Scene } from "../../shared/solomonCreatorStoryV7";
import type { SolomonStorySource } from "../../shared/solomonCreatorStory";

const INK = "#07111f";
const DEEP = "#102c4c";
const PAPER = "#f7f4ed";
const MINT = "#42e6b4";
const GREEN = "#087052";
const AMBER = "#ffbd59";
const CORAL = "#ff6f61";
const WHITE = "#fff";
const PRODUCT_FILES = { jobs: "proof-jobs.mp4", tracker: "proof-tracker.mp4", contacts: "proof-contacts.mp4", outreach: "proof-outreach.mp4" } as const;
const PRODUCT_TRIM_FRAMES: Record<string, number> = { "hook-status": 92, "hook-contact": 76, "role-company": 30, "contact-reason": 76, "draft-assembly": 65, "readable-sentence": 65, "edit-decide": 108, "connected-result": 65 };

export const SolomonCreatorStoryV7: React.FC<SolomonCreatorStoryV7Manifest> = (manifest) => <AbsoluteFill style={{ background: INK, color: WHITE, fontFamily: "Avenir Next, Manrope, Arial, sans-serif", overflow: "hidden" }}>
  {manifest.scenes.map((scene) => <Sequence key={scene.id} name={scene.id} from={scene.from} durationInFrames={scene.to - scene.from} premountFor={30}><Scene scene={scene} manifest={manifest}/></Sequence>)}
  {manifest.captions.map((caption) => <Sequence key={caption.id} name={caption.id} from={caption.from} durationInFrames={caption.to - caption.from} premountFor={12}><Caption caption={caption}/></Sequence>)}
  <Audio src={staticFile("narration.wav")}/><Audio src={staticFile("sound-design.wav")}/>
</AbsoluteFill>;

const Scene: React.FC<{scene: V7Scene; manifest: SolomonCreatorStoryV7Manifest}> = ({ scene, manifest }) => {
  const source = scene.assetId ? manifest.sources.find(({ id }) => id === scene.assetId) : undefined;
  if (scene.kind === "product") return <ProductScene scene={scene} source={source!}/>;
  if (scene.recipe === "fragmentation_collapse") return <FiveTools scene={scene}/>;
  if (scene.recipe === "evidence_to_draft") return <ContextBridge scene={scene}/>;
  if (scene.recipe === "generic_contextual") return <Comparison scene={scene}/>;
  if (scene.recipe === "connected_result") return <ConnectedResult scene={scene} sources={manifest.sources}/>;
  if (scene.recipe === "solomon_cta") return <SolomonCta scene={scene}/>;
  return <RobotStage scene={scene}/>;
};

const RobotStage: React.FC<{scene: V7Scene}> = ({ scene }) => <AbsoluteFill style={{ background: scene.narrativeFunction === "problem" ? "radial-gradient(circle at 50% 38%,#5c2630,#180d16 62%,#07111f)" : "radial-gradient(circle at 50% 35%,#15505b,#102c4c 52%,#07111f)" }}>
  <Studio warning={scene.narrativeFunction === "problem"}/>{scene.robot && <SolomonRobot direction={scene.robot}/>}<Disclosure text={scene.conceptualDisclosure}/>
</AbsoluteFill>;

export const SolomonRobot: React.FC<{direction: RobotDirection}> = ({ direction }) => {
  const frame = useCurrentFrame(); const { durationInFrames } = useVideoConfig();
  const seed = [...direction.sceneId].reduce((sum, c) => sum + c.charCodeAt(0), 0);
  const idle = sampleIrregularIdle(frame, seed); const speech = sampleSpeechEnvelope(direction.audioEnvelope, frame, durationInFrames);
  const blink = direction.blinkFrames.some((at) => frame >= at && frame <= at + 2) ? .08 : 1;
  const gaze = spring({ frame: Math.max(0, frame - direction.gazeArrivalFrame), fps: 30, config: { damping: 18, stiffness: 145 }, durationInFrames: 14 });
  const gesture = spring({ frame: Math.max(0, frame - direction.gesturePeakFrame + 9), fps: 30, config: { damping: 15, stiffness: 130 }, durationInFrames: 18 });
  const recover = interpolate(frame, [direction.gesturePeakFrame, direction.recoveryFrame], [1, .18], { extrapolateLeft: "clamp", extrapolateRight: "clamp" });
  const action = gesture * recover; const cameo = direction.scaleToken === "cameo";
  const targetX = direction.gazeTarget === "product_left" ? -18 : direction.gazeTarget === "product_right" ? 18 : 0;
  const targetY = direction.gazeTarget === "cta" ? 14 : 0;
  const pose = robotPose(direction, cameo);
  const eye = eyeGeometry(direction.eyeShape);
  const leftAction = direction.handSilhouette === "open_palm" || direction.gazeTarget === "product_left" ? action : action * .2;
  const rightAction = direction.handSilhouette === "point" || direction.handSilhouette === "wave" || direction.gazeTarget === "product_right" ? action : action * .18;
  return <div data-robot-scene={direction.sceneId} data-scale-token={direction.scaleToken} style={{ position: "absolute", width: 650, height: 930, ...pose, transform: `${pose.transform ?? ""} translate(${direction.torsoTranslateX + idle.x}px,${direction.torsoTranslateY + idle.y}px) rotate(${direction.torsoRotate}deg)`, transformOrigin: "50% 76%", zIndex: cameo ? 22 : 4 }}>
    <svg viewBox="0 0 650 930" width="650" height="930" style={{ overflow: "visible", filter: "drop-shadow(0 34px 44px rgba(0,0,0,.33))" }} aria-label="Solomon robot presenter">
      <defs><linearGradient id={`shell-${direction.sceneId}`} x1="0" y1="0" x2="1" y2="1"><stop offset="0" stopColor="#fff"/><stop offset=".58" stopColor="#e7eef3"/><stop offset="1" stopColor="#b5c3cf"/></linearGradient><filter id={`glow-${direction.sceneId}`}><feGaussianBlur stdDeviation="6" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs>
      <g transform={`translate(325 235) rotate(${direction.headRotate + idle.head}) translate(-325 -235)`}>
        <rect x="164" y="68" width="322" height="292" rx="104" fill={`url(#shell-${direction.sceneId})`} stroke="#fff" strokeWidth="9"/><rect x="187" y="100" width="276" height="208" rx="74" fill="#061522" stroke={direction.emotion === "concerned" ? CORAL : MINT} strokeOpacity=".38" strokeWidth="4"/><rect x="288" y="38" width="74" height="43" rx="20" fill="#d9e1e8"/><circle cx="325" cy="38" r="12" fill={AMBER}/><rect x="132" y="156" width="45" height="102" rx="22" fill="#c7d2dc"/><rect x="473" y="156" width="45" height="102" rx="22" fill="#c7d2dc"/>
        <g transform={`translate(${targetX * gaze} ${targetY * gaze}) scale(1 ${blink})`} style={{ transformOrigin: "325px 193px" }} filter={`url(#glow-${direction.sceneId})`}><ellipse cx="273" cy={193 + eye.leftY} rx={eye.leftRx} ry={eye.leftRy} fill={MINT} transform={`rotate(${eye.leftRotate} 273 193)`}/><ellipse cx="377" cy={193 + eye.rightY} rx={eye.rightRx} ry={eye.rightRy} fill={MINT} transform={`rotate(${eye.rightRotate} 377 193)`}/></g>
        <g transform="translate(325 260)" fill={MINT} filter={`url(#glow-${direction.sceneId})`}>{[-38,-19,0,19,38].map((x,index)=><rect key={x} x={x-5} y={-5-speech*(index===2?16:index%2?9:4)} width="10" height={10+speech*(index===2?32:index%2?18:8)} rx="5"/>)}</g>
      </g>
      <path d="M205 390 Q325 340 445 390 Q500 515 492 730 Q325 812 158 730 Q150 515 205 390Z" fill={`url(#shell-${direction.sceneId})`} stroke="#fff" strokeWidth="9"/><path d="M238 462 Q325 422 412 462 L399 612 Q325 656 251 612Z" fill={DEEP} stroke={MINT} strokeOpacity=".55" strokeWidth="5"/><circle cx="325" cy="530" r="42" fill={MINT}/><text x="325" y="548" textAnchor="middle" fill={INK} fontFamily="Arial" fontWeight="950" fontSize="47">S</text>
      <Arm side="left" amount={leftAction} silhouette={direction.handSilhouette}/><Arm side="right" amount={rightAction} silhouette={direction.handSilhouette}/><path d="M208 742 Q325 802 442 742" fill="none" stroke={AMBER} strokeWidth="10" strokeLinecap="round"/>
    </svg>
  </div>;
};

const Arm: React.FC<{side:"left"|"right"; amount:number; silhouette:RobotDirection["handSilhouette"]}> = ({ side, amount, silhouette }) => {
  const flip = side === "left" ? 1 : -1; const origin = side === "left" ? 150 : 500; const hand = side === "left" ? 103 : 547;
  const rotation = silhouette === "point" ? flip * -34 : silhouette === "open_palm" ? flip * -18 : silhouette === "wave" ? flip * -48 : flip * -7;
  return <g transform={`translate(${flip * -48 * amount} ${-112 * amount}) rotate(${rotation * amount} ${origin} 690)`}><path d={side === "left" ? "M194 450 Q104 530 105 675" : "M456 450 Q546 530 545 675"} fill="none" stroke="#d8e1e8" strokeWidth="82" strokeLinecap="round"/><circle cx={hand} cy="700" r="54" fill="#f7fafc" stroke="#c5d0da" strokeWidth="7"/>{silhouette === "point" ? <path d={side === "left" ? "M86 681 L34 621" : "M564 681 L616 621"} stroke="#f7fafc" strokeWidth="22" strokeLinecap="round"/> : <path d={side === "left" ? "M83 683 L42 638 M105 675 L92 616 M128 685 L142 628" : "M525 683 L488 636 M548 675 L548 614 M570 685 L591 630"} stroke="#f7fafc" strokeWidth="20" strokeLinecap="round"/>}</g>;
};

const ProductScene: React.FC<{scene:V7Scene; source:SolomonStorySource}> = ({ scene, source }) => {
  const frame=useCurrentFrame(); const viewport={left:36,top:250,width:1008,height:1370}; const sourceHeight=1370; const sourceWidth=sourceHeight*source.sourceWidth/source.sourceHeight;
  const progress=smooth(Math.min(1,frame/scene.camera!.settleFrames)); const zoom=scene.camera!.zoomStart+(scene.camera!.zoomEnd-scene.camera!.zoomStart)*progress; const target=scene.focusTarget!;
  const centerX=(target.x+target.width/2)*sourceWidth; const centerY=(target.y+target.height/2)*sourceHeight; const left=clamp(viewport.width*scene.camera!.anchorX-centerX*zoom,viewport.width-sourceWidth*zoom,0); const top=clamp(viewport.height*scene.camera!.anchorY-centerY*zoom,viewport.height-sourceHeight*zoom,0);
  const pointerX=left+(source.actionRegion.x+source.actionRegion.width/2)*sourceWidth*zoom; const pointerY=top+(source.actionRegion.y+source.actionRegion.height/2)*sourceHeight*zoom;
  return <AbsoluteFill style={{background:PAPER,color:INK}}><div style={{position:"absolute",...viewport,overflow:"hidden",borderRadius:32,background:WHITE,border:"2px solid #d8ddd9",boxShadow:"0 34px 85px rgba(7,17,31,.2)"}}><div style={{position:"absolute",width:sourceWidth,height:sourceHeight,left,top,transform:`scale(${zoom})`,transformOrigin:"0 0"}}><Video src={staticFile(PRODUCT_FILES[scene.assetId!])} trimBefore={PRODUCT_TRIM_FRAMES[scene.id] ?? 0} muted objectFit="fill" style={{width:"100%",height:"100%",filter:"saturate(1.06) contrast(1.025)"}}/>{source.privacyMasks.map(mask=><div key={`${mask.x}-${mask.y}`} style={{position:"absolute",left:mask.x*sourceWidth,top:mask.y*sourceHeight,width:mask.width*sourceWidth,height:mask.height*sourceHeight,borderRadius:8,background:"linear-gradient(135deg,#f7f4ed,#e4eee9)",border:"1px solid rgba(8,112,82,.3)",color:GREEN,display:"grid",placeItems:"center",fontSize:13,fontWeight:900,whiteSpace:"nowrap",overflow:"hidden"}}>{mask.label}</div>)}</div>{scene.camera!.cursorRequired&&<MousePointer x={pointerX} y={pointerY} frame={frame}/>}<ProofLabels scene={scene}/></div>{scene.robot&&<SolomonRobot direction={scene.robot}/>}<div style={{position:"absolute",top:200,left:44,color:GREEN,fontSize:18,letterSpacing:2.2,fontWeight:950}}>VERIFIED SOLOMON PRODUCT</div></AbsoluteFill>;
};

const FiveTools: React.FC<{scene:V7Scene}> = ({scene}) => { const frame=useCurrentFrame(); const labels=["JOB POST","LINKEDIN","NOTES","CONTACTS","BLANK EMAIL"]; const collapse=spring({frame:Math.max(0,frame-54),fps:30,config:{damping:16,stiffness:105},durationInFrames:35}); return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 42%,#672833,#28121b 58%,#07111f)"}}>{labels.map((label,index)=>{const enter=spring({frame:Math.max(0,frame-index*5),fps:30,config:{damping:13,stiffness:160},durationInFrames:18});const col=index%2,row=Math.floor(index/2);const x=70+col*500,y=255+row*270;return <div key={label} style={{position:"absolute",left:x+(480-x)*collapse,top:y+(760-y)*collapse,width:440-270*collapse,height:190-110*collapse,borderRadius:28,display:"grid",placeItems:"center",background:index===1?"#0a66c2":"rgba(255,255,255,.1)",border:"2px solid rgba(255,255,255,.24)",fontSize:27,fontWeight:950,transform:`rotate(${(col?1:-1)*(4+index)*(1-collapse)}deg) scale(${.82+enter*.18})`,opacity:enter*(1-collapse*.15)}}><span>{collapse>.72?"CONTEXT":label}</span></div>})}<div style={{position:"absolute",left:478,top:760,width:124,height:124,borderRadius:62,background:MINT,color:INK,display:"grid",placeItems:"center",fontSize:58,fontWeight:950,transform:`scale(${collapse})`}}>S</div>{scene.robot&&<SolomonRobot direction={scene.robot}/>}<Disclosure text={scene.conceptualDisclosure}/></AbsoluteFill>};

const ContextBridge: React.FC<{scene:V7Scene}> = ({scene}) => {const frame=useCurrentFrame();const p=spring({frame,fps:30,config:{damping:16,stiffness:110},durationInFrames:32});return <AbsoluteFill style={{background:`linear-gradient(145deg,${DEEP},${INK})`}}><div style={{position:"absolute",left:80,top:390,width:370,height:480,borderRadius:34,background:WHITE,color:INK,padding:30}}><b style={{fontSize:28,color:GREEN}}>OPPORTUNITY</b><p style={{fontSize:38,fontWeight:900}}>Senior Product Engineer<br/>Faire</p></div><div style={{position:"absolute",right:70,top:390,width:390,height:480,borderRadius:34,border:`4px solid ${MINT}`,padding:30}}><b style={{fontSize:28,color:MINT}}>MESSAGE</b><div style={{marginTop:75,height:14,background:"rgba(255,255,255,.22)",borderRadius:8}}/><div style={{marginTop:24,height:14,background:"rgba(255,255,255,.22)",borderRadius:8}}/></div>{["ROLE","COMPANY","REASON"].map((label,index)=><div key={label} style={{position:"absolute",left:310+(300*p),top:910+index*72-(360*p),padding:"12px 18px",borderRadius:999,background:index===2?AMBER:MINT,color:INK,fontSize:19,fontWeight:950,transform:`scale(${.85+p*.15})`}}>{label}</div>)}{scene.robot&&<SolomonRobot direction={scene.robot}/>}</AbsoluteFill>};

const Comparison: React.FC<{scene:V7Scene}> = ({scene}) => <AbsoluteFill style={{background:PAPER,color:INK}}><div style={{position:"absolute",left:48,right:48,top:310,display:"grid",gridTemplateColumns:"1fr 1fr",gap:20}}><CompareCard title="GENERIC" body="Hi, I wanted to connect about the role." color={CORAL}/><CompareCard title="GROUNDED" body="I'm reaching out about the Senior Product Engineer role at Faire." color={GREEN}/></div>{scene.robot&&<SolomonRobot direction={scene.robot}/>}<Disclosure text={scene.conceptualDisclosure}/></AbsoluteFill>;
const CompareCard:React.FC<{title:string;body:string;color:string}>=({title,body,color})=><div style={{minHeight:620,borderRadius:34,background:WHITE,border:`4px solid ${color}`,padding:30,boxShadow:"0 24px 65px rgba(7,17,31,.14)"}}><div style={{color,fontSize:24,fontWeight:950,letterSpacing:2}}>{title}</div><div style={{marginTop:70,fontSize:35,lineHeight:1.25,fontWeight:850}}>{body}</div></div>;

const ConnectedResult:React.FC<{scene:V7Scene;sources:SolomonStorySource[]}>=({scene})=> <AbsoluteFill style={{background:"radial-gradient(circle at 50% 44%,#148269,#0a342f 58%,#07111f)"}}><div style={{position:"absolute",left:55,right:55,top:260,bottom:270,borderRadius:38,overflow:"hidden",background:WHITE,boxShadow:"0 34px 90px rgba(0,0,0,.28)"}}><Video src={staticFile(PRODUCT_FILES.outreach)} trimBefore={65} muted objectFit="cover" style={{width:"100%",height:"100%",transform:"scale(1.32)",filter:"saturate(1.06) contrast(1.02)"}}/><div style={{position:"absolute",inset:0,background:"linear-gradient(180deg,transparent 58%,rgba(7,17,31,.88))"}}/><div style={{position:"absolute",left:24,right:24,bottom:26,display:"flex",gap:10,flexWrap:"wrap"}}>{["ROLE","PERSON","EVIDENCE","EDITABLE MESSAGE"].map((x,i)=><span key={x} style={{padding:"10px 16px",borderRadius:999,background:i===3?MINT:WHITE,color:INK,fontSize:18,fontWeight:950}}>{x}</span>)}</div></div>{scene.robot&&<SolomonRobot direction={scene.robot}/>}</AbsoluteFill>;

const SolomonCta:React.FC<{scene:V7Scene}>=({scene})=>{const frame=useCurrentFrame();if(scene.id==="solomon-sting")return <AbsoluteFill style={{background:INK,display:"grid",placeItems:"center"}}><div style={{textAlign:"center"}}><div style={{fontSize:96,fontWeight:950,letterSpacing:7}}>SOLOMON</div><div style={{color:MINT,fontSize:25,fontWeight:900,letterSpacing:4,marginTop:12}}>YOUR NEXT STEP, CONNECTED</div></div></AbsoluteFill>;const enter=spring({frame,fps:30,config:{damping:17,stiffness:125},durationInFrames:25});return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 34%,#15505b,#102c4c 54%,#07111f)"}}><Studio warning={false}/>{scene.robot&&<SolomonRobot direction={scene.robot}/>}<div style={{position:"absolute",left:74,right:74,bottom:110,padding:"28px 32px",borderRadius:32,background:WHITE,color:INK,border:`4px solid ${MINT}`,textAlign:"center",transform:`translateY(${(1-enter)*70}px)`}}><div style={{fontSize:28,color:GREEN,fontWeight:950,letterSpacing:2}}>SOLOMON</div><div style={{fontSize:55,fontWeight:950,lineHeight:1.02,marginTop:8}}>SAVE THIS WORKFLOW</div></div></AbsoluteFill>};

const ProofLabels:React.FC<{scene:V7Scene}>=({scene})=>{const labels:Record<string,string[]>={"hook-status":["INTERVIEWING"],"hook-contact":["RELEVANT CONTACT"],"role-company":["ROLE","COMPANY"],"contact-reason":["TARGET COMPANY","HIRING FUNCTION","VERIFIED"],"draft-assembly":["ROLE","COMPANY","REASON","ASK"],"readable-sentence":["CONTEXTUAL SENTENCE"],"edit-decide":["DRAFT — NOT SENT","EDIT"],"connected-result":["READY FOR REVIEW"]};return <div style={{position:"absolute",left:22,right:22,bottom:22,zIndex:12,display:"flex",justifyContent:"center",gap:9,flexWrap:"wrap"}}>{(labels[scene.id]??[]).map((label,index)=><span key={label} style={{padding:"10px 15px",borderRadius:999,background:index===0?GREEN:WHITE,color:index===0?WHITE:INK,border:`2px solid ${GREEN}`,fontSize:18,fontWeight:950}}>{label}</span>)}</div>};
const MousePointer:React.FC<{x:number;y:number;frame:number}>=({x,y,frame})=>{const enter=spring({frame,fps:30,config:{damping:18,stiffness:110},durationInFrames:22});const tap=interpolate(frame,[18,22,27],[1,.8,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <svg aria-label="Mouse pointer" viewBox="0 0 40 52" width="52" height="68" style={{position:"absolute",zIndex:18,left:x-8+(1-enter)*90,top:y-8+(1-enter)*62,transform:`scale(${tap})`,filter:"drop-shadow(0 3px 4px rgba(0,0,0,.38))"}}><path d="M4 3 L4 39 L14 30 L22 48 L30 44 L22 27 L36 27 Z" fill="#fff" stroke="#111827" strokeWidth="3" strokeLinejoin="round"/></svg>};

const Caption:React.FC<{caption:V7Caption}>=({caption})=>{const frame=useCurrentFrame();const {durationInFrames}=useVideoConfig();const enter=spring({frame,fps:30,config:{damping:16,stiffness:175},durationInFrames:Math.min(14,durationInFrames)});const exit=caption.role==="cta"?1:interpolate(frame,[Math.max(0,durationInFrames-4),durationInFrames],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const words=caption.text.split(" ");return <div style={{position:"absolute",left:48,right:48,zIndex:60,...captionPlacement(caption.placement),display:"flex",justifyContent:"center",flexWrap:"wrap",gap:"7px 12px",opacity:exit,transform:`translateY(${(1-enter)*38}px) scale(${.88+enter*.12})`}}>{words.map((word,index)=>{const emphasized=caption.emphasis.some(x=>word.includes(x));return <span key={`${word}-${index}`} style={{padding:emphasized?"7px 12px":"7px 1px",borderRadius:12,background:emphasized?MINT:"rgba(7,17,31,.8)",color:emphasized?INK:WHITE,fontFamily:caption.role==="memory_anchor"?"Georgia, Instrument Serif, serif":"Avenir Next, Manrope, Arial, sans-serif",fontStyle:caption.role==="memory_anchor"?"italic":"normal",fontSize:caption.role==="cta"?66:caption.role==="memory_anchor"?75:54,lineHeight:.98,fontWeight:950,letterSpacing:-1.5}}>{word}</span>})}</div>};

const Studio:React.FC<{warning:boolean}>=({warning})=>{const frame=useCurrentFrame();return <AbsoluteFill style={{overflow:"hidden"}}><div style={{position:"absolute",left:-130,top:230,width:480,height:720,background:warning?"rgba(255,111,97,.18)":"rgba(66,230,180,.13)",filter:"blur(95px)",transform:`translateX(${Math.sin(frame/31)*14}px)`}}/><div style={{position:"absolute",right:60,top:250,width:270,height:500,border:"2px solid rgba(255,255,255,.1)",borderRadius:34,background:"linear-gradient(145deg,rgba(255,255,255,.08),rgba(255,255,255,.015))"}}/><div style={{position:"absolute",left:-40,right:-40,bottom:-90,height:330,background:"linear-gradient(#17283d,#080f19)",transform:"perspective(650px) rotateX(65deg)",transformOrigin:"bottom"}}/></AbsoluteFill>};
const Disclosure:React.FC<{text?:string}>=({text})=>text?<div style={{position:"absolute",left:44,bottom:50,padding:"9px 15px",borderRadius:11,background:"rgba(7,17,31,.78)",fontSize:15,fontWeight:800,letterSpacing:1}}>{text}</div>:null;
function robotPose(direction:RobotDirection,cameo:boolean):CSSProperties{if(cameo){if(direction.gazeTarget==="product_left")return{right:-92,bottom:110,transform:"scale(.56)"};return{left:-92,bottom:110,transform:"scale(.56)"}}return{left:"50%",top:310,transform:"translateX(-50%) scale(1.02)"}}
function eyeGeometry(shape:RobotDirection["eyeShape"]){if(shape==="surprised_round")return{leftRx:30,leftRy:28,rightRx:30,rightRy:28,leftY:0,rightY:0,leftRotate:0,rightRotate:0};if(shape==="curious_asymmetric")return{leftRx:29,leftRy:18,rightRx:24,rightRy:13,leftY:-5,rightY:4,leftRotate:-7,rightRotate:7};if(shape==="concerned_inner_raise")return{leftRx:27,leftRy:14,rightRx:27,rightRy:14,leftY:1,rightY:1,leftRotate:-12,rightRotate:12};if(shape==="focused_narrow")return{leftRx:29,leftRy:9,rightRx:29,rightRy:9,leftY:0,rightY:0,leftRotate:0,rightRotate:0};if(shape==="relieved_curve")return{leftRx:27,leftRy:10,rightRx:27,rightRy:10,leftY:7,rightY:7,leftRotate:-4,rightRotate:4};return{leftRx:28,leftRy:13,rightRx:28,rightRy:13,leftY:0,rightY:0,leftRotate:0,rightRotate:0}}
function captionPlacement(placement:V7Caption["placement"]):CSSProperties{if(placement==="top")return{top:110};if(placement==="center")return{top:690};if(placement==="lower")return{bottom:95};return{bottom:315}}
function smooth(value:number){return value*value*(3-2*value)} function clamp(value:number,minimum:number,maximum:number){return Math.max(minimum,Math.min(maximum,value))}
