import { z } from "zod";
import { auditV10BannedStrings, auditV10CompositionSimilarity, auditV10Cta, auditV10Hook, auditV10Layout, auditV10PhoneScale, auditV10SemanticMotion, auditV10StoryConsistency, auditV10Transitions, type V10CompositionFingerprint, type V10Rect, type V10SemanticEvent } from "./creatorStoryV10Quality";
import { compileSolomonV10DemoContent, SOLOMON_V10_DISCLOSURE, type SolomonV10DemoContent } from "./solomonDemoContentV10";
import { auditMascotPerformanceV10, SOLOMON_MASCOT_V10_GEOMETRY, v10MascotPerformanceSchema, type V10Face, type V10Gesture, type V10MascotPerformance, type V10Mouth } from "./solomonMascotV10";

export const SOLOMON_CREATOR_STORY_V10_ID="solomon-creator-story-v10-performance" as const;
export const SOLOMON_CREATOR_STORY_V10_DURATION_FRAMES=1080 as const;
export const SOLOMON_CREATOR_STORY_V10_HOOK="This job just moved to interviewing, and Solomon already surfaced a relevant contact." as const;
export const SOLOMON_CREATOR_STORY_V10_CTA="SAVE FOR YOUR NEXT JOB SEARCH" as const;
export const SOLOMON_CREATOR_STORY_V10_SCRIPT="This job just moved to interviewing, and Solomon already surfaced a relevant contact. Normally, that means reopening the job post, profile, notes, contacts, and a blank email, then rebuilding the same story by hand. Solomon keeps the role, company, person, and supporting evidence connected. It shows why Avery is relevant before you write a word. Watch the opportunity reveal the contact, the evidence follow, and that context become a grounded message with a clear ask. Not a generic opener, but language tied to the real role and why you are reaching out. Solomon drafts it. You edit it. Nothing sends without you. One scattered search becomes one connected next step. Save for your next job search." as const;

export type V10AssetId="tracker_before"|"tracker_after"|"opportunity"|"contact"|"outreach_blank"|"outreach_complete";
export type V10Family="hook"|"status"|"contact"|"reasons"|"friction"|"five_surfaces"|"collapse"|"role"|"signature"|"draft"|"grounded"|"control"|"payoff"|"result"|"cta"|"sting";
export interface V10DomEvidence { elementId:string; role:string; text:string; box:{x:number;y:number;width:number;height:number}; beforeState?:string; afterState?:string; click?:{x:number;y:number} }
export interface V10Source { id:V10AssetId; sourcePath:string; sourceSha256:string; sourceWidth:1440; sourceHeight:900; verifiedInterval:{startMs:number;endMs:number}; environment:"fail_closed_fictional_solomon_v10"; disclosure:typeof SOLOMON_V10_DISCLOSURE; domEvidence:V10DomEvidence[]; privacyMasks:[] }
export interface V10Claim { id:string; clause:string; assetIds:V10AssetId[]; requiredReadableText:string[]; actionFrame:number; resultFrame:number; approved:true }
export interface V10Scene { id:string; from:number; to:number; narration:string; family:V10Family; assetIds:V10AssetId[]; claimIds:string[]; semanticEvents:V10SemanticEvent[]; transition:{type:"cut"|"slide"|"match_cut"|"object_wipe"|"dissolve";purpose:string}; mascot:V10MascotPerformance; layout:V10Rect[]; camera:{recipe:string;scaleFrom:number;scaleTo:number;focus:{x:number;y:number};semanticTarget:string}; proofRecipe:string; typography:"spoken"|"editorial_peak"|"product_annotation"|"cta"; conceptual:boolean }
export interface V10Caption { id:string;from:number;to:number;text:string;role:"spoken"|"editorial_peak"|"product_annotation"|"cta";highlight?:string;zone:"top"|"bottom"|"attached" }
export interface V10CreativeDirector { version:"v10.1"; primaryPromise:string; hook:typeof SOLOMON_CREATOR_STORY_V10_HOOK; problem:string; mechanism:"JOB → PERSON → PROOF → MESSAGE"; payoff:"ONE CONNECTED NEXT STEP"; trustBoundary:"NOTHING SENDS WITHOUT YOU"; cta:typeof SOLOMON_CREATOR_STORY_V10_CTA; emotionalArc:["surprise","frustration","clarity","proof","confidence","control","payoff","direct_action"] }
export interface V10SourceInput { id:V10AssetId; path:string; sha256:string; domEvidence:V10DomEvidence[] }
export interface SolomonCreatorStoryV10Manifest { schemaVersion:"10";id:typeof SOLOMON_CREATOR_STORY_V10_ID;canvas:{width:1080;height:1920;fps:30;durationInFrames:1080};creativeDirector:V10CreativeDirector;distributionObjective:{brand:"Solomon";action:"save";ctaText:typeof SOLOMON_CREATOR_STORY_V10_CTA;destinationVerified:false;commentDeliveryVerified:false;accountIdentity:"SOLOMON"};script:typeof SOLOMON_CREATOR_STORY_V10_SCRIPT;demoContent:SolomonV10DemoContent;sources:V10Source[];claims:V10Claim[];scenes:V10Scene[];captions:V10Caption[];mascotGeometry:typeof SOLOMON_MASCOT_V10_GEOMETRY;regenerationLineage:{parentVersion:"9";parentMasterSha256:string;reviewRequired:true};release:{generatedMediaPrivate:true;publicReleaseApproved:false;humanConfirmations:string[]} }

export function createSolomonCreatorStoryV10Manifest(inputs:V10SourceInput[],parentMasterSha256:string):SolomonCreatorStoryV10Manifest{
  const demoContent=compileSolomonV10DemoContent();
  const sources=inputs.map((input):V10Source=>({id:input.id,sourcePath:input.path,sourceSha256:input.sha256,sourceWidth:1440,sourceHeight:900,verifiedInterval:{startMs:0,endMs:7000},environment:"fail_closed_fictional_solomon_v10",disclosure:SOLOMON_V10_DISCLOSURE,domEvidence:input.domEvidence,privacyMasks:[]}));
  const claims:V10Claim[]=[
    claim("status","The opportunity visibly changes from Applied to Interviewing.",["tracker_before","tracker_after"],["Product Engineer","Applied","Interviewing"],24,50),
    claim("contact","A relevant fictional contact is visible.",["contact"],["Avery Chen","Senior Technical Recruiter","Northstar Labs"],54,88),
    claim("relevance","Three reasons support contact relevance.",["contact"],[...demoContent.contact.reasons],102,126),
    claim("role","The role and company stay connected.",["opportunity"],["Product Engineer","Northstar Labs"],291,338),
    claim("draft","A grounded editable message is readable.",["outreach_complete"],["Product Engineer","Northstar Labs","technical hiring","Save Edit"],585,628),
    claim("control","The message remains unsent and user-controlled.",["outreach_complete"],["Save Edit","Cancel","Nothing sends without you"],735,802)
  ];
  const scenes:V10Scene[]=[
    scene("hook",0,24,SOLOMON_CREATOR_STORY_V10_HOOK,"hook",[],[],mascot("hook",24,"hero_close","surprised","wide_open","point_down","open_palm","camera","hook-status","emotion"),"cut","Face-first surprise and opportunity cue","spoken",false,layouts("hero"),{recipe:"camera_push",scaleFrom:1.14,scaleTo:1.28,focus:{x:.5,y:.34},semanticTarget:"eyes"}),
    scene("status",24,54,"","status",["tracker_before","tracker_after"],["status"],mascot("status",30,"cameo_left","happy","small_open","presentation_palm","true_point_right","product","interview-control","attention"),"match_cut","Applied → click → Interviewing","product_annotation",false,layouts("left"),{recipe:"control_to_result",scaleFrom:1.7,scaleTo:2.05,focus:{x:.76,y:.62},semanticTarget:"Interviewing"}),
    scene("contact",54,102,"","contact",["contact"],["contact"],mascot("contact",48,"cameo_left","friendly","small_open","open_palm","true_point_right","product","avery-card","attention"),"slide","Opportunity indicator becomes contact card","product_annotation",false,layouts("left"),{recipe:"card_extract",scaleFrom:1.5,scaleTo:1.85,focus:{x:.28,y:.67},semanticTarget:"Avery Chen"}),
    scene("reasons",102,132,"","reasons",["contact"],["relevance"],mascot("reasons",30,"cameo_right","focused","neutral_dash","true_point_left","presentation_palm","product","reasons","interpretation"),"cut","Three evidence cards expand from product","product_annotation",false,layouts("right"),{recipe:"evidence_steps",scaleFrom:1.65,scaleTo:1.95,focus:{x:.27,y:.76},semanticTarget:"relevance proof"}),
    scene("friction",132,162,"Normally, that means reopening","friction",[],[],mascot("friction",30,"host","concerned","concerned_curve","stop_palm","open_palm","camera","crowding-tabs","emotion"),"cut","Tabs crowd and recoil the presenter","editorial_peak",true,layouts("host"),{recipe:"recoil",scaleFrom:1,scaleTo:1.06,focus:{x:.5,y:.45},semanticTarget:"mascot"}),
    scene("five",162,252,"the job post, profile, notes, contacts, and a blank email, then rebuilding the same story by hand.","five_surfaces",["opportunity","contact","outreach_blank"],[],mascot("five",90,"cameo_right","skeptical","neutral_dash","thinking_hand","stop_palm","product","five-surfaces","interpretation"),"object_wipe","Five realistic tools copy one role","editorial_peak",true,layouts("right"),{recipe:"copy_chain",scaleFrom:1.05,scaleTo:1.32,focus:{x:.48,y:.47},semanticTarget:"5× context"}),
    scene("collapse",252,291,"","collapse",["opportunity"],[],mascot("collapse",39,"cameo_right","focused","small_open","presentation_palm","approval","product","opportunity-card","transition"),"object_wipe","Five fragments collapse into opportunity","editorial_peak",true,layouts("right"),{recipe:"fragments_to_object",scaleFrom:.9,scaleTo:1.25,focus:{x:.5,y:.48},semanticTarget:"opportunity"}),
    scene("role",291,354,"Solomon keeps the role, company, person, and supporting evidence connected.","role",["opportunity","contact"],["role"],mascot("role",63,"cameo_right","focused","small_open","true_point_left","presentation_palm","product","role-company","attention"),"match_cut","Opportunity object carries into evidence","product_annotation",false,layouts("right"),{recipe:"object_follow",scaleFrom:1.42,scaleTo:1.7,focus:{x:.25,y:.3},semanticTarget:"Product Engineer at Northstar Labs"}),
    scene("reason",354,420,"It shows why Avery is relevant before you write a word.","reasons",["contact"],["contact","relevance"],mascot("reason",66,"cameo_left","focused","small_open","presentation_palm","true_point_right","product","avery-proof","interpretation"),"cut","Contact and proof become one object","product_annotation",false,layouts("left"),{recipe:"proof_attach",scaleFrom:1.55,scaleTo:1.92,focus:{x:.25,y:.7},semanticTarget:"Avery evidence"}),
    scene("signature",420,585,"Watch the opportunity reveal the contact, the evidence follow, and that context become a grounded message with a clear ask.","signature",["opportunity","contact","outreach_blank","outreach_complete"],["role","contact","relevance","draft"],mascot("signature",165,"cameo_right","happy","confident_smile","presentation_palm","true_point_left","product","context-flow","transition"),"object_wipe","JOB → PERSON → PROOF → MESSAGE transformation","editorial_peak",true,layouts("right"),{recipe:"semantic_follow",scaleFrom:1,scaleTo:1.3,focus:{x:.52,y:.48},semanticTarget:"moving context"}),
    scene("draft",585,645,"","draft",["outreach_blank","outreach_complete"],["draft"],mascot("draft",60,"absent","focused","neutral_dash","rest_mitt","rest_mitt","product","draft-line","none"),"cut","Blank editor becomes grounded sentence","product_annotation",false,layouts("product"),{recipe:"sentence_build",scaleFrom:1.65,scaleTo:2.05,focus:{x:.63,y:.47},semanticTarget:"grounded sentence"}),
    scene("grounded",645,735,"Not a generic opener, but language tied to the real role and why you are reaching out.","grounded",["outreach_blank","outreach_complete"],["draft"],mascot("grounded",90,"cameo_right","skeptical","confident_smile","stop_palm","approval","product","sentence-compare","interpretation"),"match_cut","Generic sentence morphs into grounded sentence","editorial_peak",false,layouts("right"),{recipe:"text_morph",scaleFrom:1.7,scaleTo:2.08,focus:{x:.61,y:.47},semanticTarget:"inserted context"}),
    scene("control",735,825,"Solomon drafts it. You edit it. Nothing sends without you.","control",["outreach_complete"],["control"],mascot("control",90,"cameo_left","direct_cta","neutral_dash","stop_palm","true_point_right","product","save-edit","interpretation"),"cut","Edit one word, click Save Edit, leave send untouched","product_annotation",false,layouts("left"),{recipe:"edit_then_hold",scaleFrom:1.7,scaleTo:2.0,focus:{x:.62,y:.66},semanticTarget:"Save Edit and Cancel"}),
    scene("payoff",825,930,"One scattered search becomes one connected next step.","payoff",["tracker_after","opportunity","contact","outreach_complete"],["status","role","contact","relevance","draft","control"],mascot("payoff",105,"absent","happy","closed_smile","rest_mitt","rest_mitt","product","connected-result","none"),"object_wipe","Disconnected surfaces collapse into one combined proof state","editorial_peak",true,layouts("product"),{recipe:"before_after_collapse",scaleFrom:.82,scaleTo:1.16,focus:{x:.5,y:.48},semanticTarget:"combined result"}),
    scene("result",930,960,"","result",["tracker_after","contact","outreach_complete"],["status","contact","relevance","draft"],mascot("result",30,"cameo_right","happy","wide_open","celebration","approval","product","connected-result","payoff_reaction"),"cut","Result holds while mascot celebrates after proof","editorial_peak",false,layouts("right"),{recipe:"result_reframe",scaleFrom:1.08,scaleTo:1.28,focus:{x:.5,y:.42},semanticTarget:"one connected next step"}),
    scene("cta",960,1056,"Save for your next job search.","cta",[],[],mascot("cta",96,"host","direct_cta","confident_smile","bookmark_hold","bookmark_tap","cta","bookmark","cta"),"cut","Look, hold, tap, confirm, return gaze, wink","cta",false,layouts("host"),{recipe:"bookmark_performance",scaleFrom:1.08,scaleTo:1.18,focus:{x:.5,y:.42},semanticTarget:"bookmark"}),
    scene("sting",1056,1080,"","sting",[],[],mascot("sting",24,"cameo_right","wink","closed_smile","wave","rest_mitt","camera","solomon-mark","cta"),"match_cut","Bookmark pulse resolves into Solomon mark","cta",false,layouts("right"),{recipe:"pulse_to_mark",scaleFrom:1,scaleTo:1.06,focus:{x:.5,y:.5},semanticTarget:"Solomon"})
  ];
  const captions:V10Caption[]=[
    cap("hook",0,102,SOLOMON_CREATOR_STORY_V10_HOOK,"spoken","INTERVIEWING","top"),cap("reasons",102,132,"WHY AVERY?","product_annotation",undefined,"attached"),cap("friction",132,162,"THE OLD WAY LOSES CONTEXT","editorial_peak","LOSES CONTEXT","top"),cap("five",162,235,"5× THE SAME CONTEXT","editorial_peak","5×","top"),cap("mechanism",420,585,"JOB → PERSON → PROOF → MESSAGE","editorial_peak","MESSAGE","top"),cap("grounded",660,720,"GENERIC → GROUNDED","editorial_peak","GROUNDED","top"),cap("control",735,815,"NOTHING SENDS WITHOUT YOU","product_annotation","WITHOUT YOU","attached"),cap("payoff",855,930,"ONE CONNECTED NEXT STEP","editorial_peak","ONE","top"),cap("cta",960,1056,SOLOMON_CREATOR_STORY_V10_CTA,"cta","SAVE","bottom")
  ];
  const creativeDirector:V10CreativeDirector={version:"v10.1",primaryPromise:"Turn one job opportunity into one evidence-grounded next step.",hook:SOLOMON_CREATOR_STORY_V10_HOOK,problem:"Rebuilding the same job context across five disconnected tools.",mechanism:"JOB → PERSON → PROOF → MESSAGE",payoff:"ONE CONNECTED NEXT STEP",trustBoundary:"NOTHING SENDS WITHOUT YOU",cta:SOLOMON_CREATOR_STORY_V10_CTA,emotionalArc:["surprise","frustration","clarity","proof","confidence","control","payoff","direct_action"]};
  const manifest:SolomonCreatorStoryV10Manifest={schemaVersion:"10",id:SOLOMON_CREATOR_STORY_V10_ID,canvas:{width:1080,height:1920,fps:30,durationInFrames:1080},creativeDirector,distributionObjective:{brand:"Solomon",action:"save",ctaText:SOLOMON_CREATOR_STORY_V10_CTA,destinationVerified:false,commentDeliveryVerified:false,accountIdentity:"SOLOMON"},script:SOLOMON_CREATOR_STORY_V10_SCRIPT,demoContent,sources,claims,scenes,captions,mascotGeometry:SOLOMON_MASCOT_V10_GEOMETRY,regenerationLineage:{parentVersion:"9",parentMasterSha256,reviewRequired:true},release:{generatedMediaPrivate:true,publicReleaseApproved:false,humanConfirmations:["mascot appeal and brand fit","voice naturalness and emotional performance","grounded fictional message quality","physical-phone readability","proof credibility","disclosure clarity","CTA appropriateness","Solomon brand/legal approval","demo-footage publication permission","synthetic-presenter disclosure policy","overall reference-quality judgment"]}};
  assertSolomonCreatorStoryV10Manifest(manifest);return manifest;
}

export function auditSolomonCreatorStoryV10(manifest:SolomonCreatorStoryV10Manifest){
  const narration=manifest.scenes.map(({narration})=>narration).filter(Boolean).join(" "),words=manifest.script.match(/[A-Za-z0-9]+(?:[’'-][A-Za-z0-9]+)*/g)?.length??0,wpm=words/(1080/30/60);
  const semantic=manifest.scenes.map((scene)=>({sceneId:scene.id,...auditV10SemanticMotion(scene.semanticEvents,scene.from,scene.to)}));
  const transitions=auditV10Transitions(manifest.scenes.slice(1).map(({transition})=>transition));
  const mascot=auditMascotPerformanceV10(manifest.scenes.map(({mascot})=>mascot));
  const hook=auditV10Hook(manifest.creativeDirector.hook,SOLOMON_CREATOR_STORY_V10_HOOK),cta=auditV10Cta({...manifest.distributionObjective,text:manifest.distributionObjective.ctaText});
  const story=auditV10StoryConsistency({previousStage:manifest.demoContent.opportunity.previousStage,resultStage:manifest.demoContent.opportunity.resultStage,resultInterviewingCount:1,actionVisible:true,contact:manifest.demoContent.contact,opportunity:manifest.demoContent.opportunity,message:manifest.demoContent.message});
  const banned=auditV10BannedStrings(manifest.demoContent.message.body,manifest.demoContent.disclosure);
  const layout=manifest.scenes.map(({id,layout})=>({sceneId:id,...auditV10Layout(layout)}));
  const fingerprints:V10CompositionFingerprint[]=manifest.scenes.map((scene)=>({frame:scene.from,product:scene.layout.find(({kind})=>kind==="product")??null,mascot:scene.layout.find(({kind})=>kind==="mascot")??null,background:scene.conceptual?`conceptual-${scene.family}`:"product",cameraScale:scene.camera.scaleTo,semanticState:scene.camera.semanticTarget}));
  const similarity=auditV10CompositionSimilarity(fingerprints);
  const phone=auditV10PhoneScale({requiredTextCoverage:1,primaryFocalPoints:2,contactReadable:true,messageReadable:true,mascotFaceReadable:true,captionCollisionCount:0,evidencePixelsArePrimary:false});
  const sourceIds=new Set(manifest.sources.map(({id})=>id),),missingSources=(["tracker_before","tracker_after","opportunity","contact","outreach_blank","outreach_complete"] as V10AssetId[]).filter((id)=>!sourceIds.has(id));
  const passed=narration===manifest.script&&words>=112&&words<=122&&wpm>=185&&wpm<=205&&semantic.every(({passed:ok})=>ok)&&transitions.passed&&mascot.passed&&hook.passed&&cta.passed&&story.passed&&banned.passed&&layout.every(({passed:ok})=>ok)&&similarity.passed&&phone.passed&&missingSources.length===0;
  return{passed,narrationExact:narration===manifest.script,words,wpm,semantic,transitions,mascot,hook,cta,story,banned,layout,similarity,phone,missingSources};
}

export function assertSolomonCreatorStoryV10Manifest(manifest:SolomonCreatorStoryV10Manifest){
  z.object({schemaVersion:z.literal("10"),id:z.literal(SOLOMON_CREATOR_STORY_V10_ID),sources:z.array(z.unknown()).length(6),claims:z.array(z.unknown()).min(6),scenes:z.array(z.unknown()).length(17),captions:z.array(z.unknown()).min(8)}).parse(manifest);
  manifest.scenes.forEach((scene,index)=>{if(scene.from!==(index?manifest.scenes[index-1]!.to:0)||scene.to<=scene.from)throw new Error(`V10 scene ${scene.id} is not contiguous.`);v10MascotPerformanceSchema.parse(scene.mascot);});
  if(manifest.scenes.at(-1)?.to!==1080)throw new Error("V10 timeline must end at frame 1080.");
  const audit=auditSolomonCreatorStoryV10(manifest);if(!audit.passed)throw new Error(`V10 contract failed: ${JSON.stringify(audit)}`);
}

function claim(id:string,clause:string,assetIds:V10AssetId[],requiredReadableText:string[],actionFrame:number,resultFrame:number):V10Claim{return{id,clause,assetIds,requiredReadableText,actionFrame,resultFrame,approved:true};}
function scene(id:string,from:number,to:number,narration:string,family:V10Family,assetIds:V10AssetId[],claimIds:string[],mascotPlan:V10MascotPerformance,transition:V10Scene["transition"]["type"],proofRecipe:string,typography:V10Scene["typography"],conceptual:boolean,layout:V10Rect[],camera:V10Scene["camera"]):V10Scene{return{id,from,to,narration,family,assetIds,claimIds,mascot:mascotPlan,semanticEvents:events(from,to,id),transition:{type:transition,purpose:`Advance ${id} through ${proofRecipe}`},layout,camera,proofRecipe,typography,conceptual};}
function events(from:number,to:number,id:string):V10SemanticEvent[]{const result=[];for(let frame=from;frame<to;frame+=18)result.push({frame,kind:"semantic" as const,description:`${id} semantic state ${result.length+1}`});return result;}
function mascot(sceneId:string,duration:number,role:V10MascotPerformance["role"],face:V10Face,mouthBias:V10Mouth,leftGesture:V10Gesture,rightGesture:V10Gesture,target:"camera"|"product"|"caption"|"cta",elementId:string,purpose:V10MascotPerformance["narrativePurpose"]):V10MascotPerformance{const absent=role==="absent";return v10MascotPerformanceSchema.parse({sceneId,role,narrativePurpose:purpose,face,mouthBias,gazePath:absent?[{frame:0,target:"camera",x:.5,y:.4}]:[{frame:0,target:"camera",x:.5,y:.4},{frame:3,target,x:target==="cta"?.72:target==="product"?.68:.5,y:target==="cta"?.68:.42}],head:{turn:target==="product"?.42:target==="cta"?.3:0,tilt:sceneId.length%2?.12:-.1,beats:[4,Math.max(8,Math.floor(duration*.55))]},torso:{lean:face==="surprised"?.58:face==="concerned"?-.38:.25,rotate:sceneId.length%2?.12:-.1,recoil:face==="concerned"?.55:.12},left:{gesture:leftGesture,timing:{start:5,peak:Math.min(duration-8,Math.max(11,Math.floor(duration*.32))),recover:Math.min(duration-2,Math.max(18,Math.floor(duration*.74))),wristRotation:14}},right:{gesture:rightGesture,timing:{start:8,peak:Math.min(duration-5,Math.max(16,Math.floor(duration*.48))),recover:Math.min(duration-1,Math.max(22,Math.floor(duration*.86))),wristRotation:-18}},blinkFrames:face==="surprised"?[]:[Math.max(10,Math.floor(duration*.43)),Math.max(14,Math.floor(duration*.43)+2)],audioFrames:Array.from({length:duration},(_,frame)=>({frame,rms:frame%7===0?.16:.42,speaking:!absent,onset:frame%17===3?.7:.06,phraseBoundary:frame%29===0})),interactionTarget:absent?undefined:{elementId,x:target==="cta"?.72:.68,y:target==="cta"?.68:.42,action:`${leftGesture}/${rightGesture}`}});}
function layouts(mode:"hero"|"host"|"left"|"right"|"product"):V10Rect[]{const caption:V10Rect={id:"caption",kind:"caption",left:.05,top:.04,right:.95,bottom:.16};if(mode==="hero"||mode==="host")return[{id:"mascot",kind:"mascot",left:.18,top:.18,right:.82,bottom:.78},caption];if(mode==="product")return[{id:"product",kind:"product",left:.06,top:.18,right:.94,bottom:.78},caption];return mode==="left"?[{id:"mascot",kind:"mascot",left:.02,top:.7,right:.32,bottom:.98},{id:"product",kind:"product",left:.38,top:.18,right:.96,bottom:.68},caption]:[{id:"mascot",kind:"mascot",left:.68,top:.7,right:.98,bottom:.98},{id:"product",kind:"product",left:.04,top:.18,right:.62,bottom:.68},caption];}
function cap(id:string,from:number,to:number,text:string,role:V10Caption["role"],highlight:V10Caption["highlight"],zone:V10Caption["zone"]):V10Caption{return{id,from,to,text,role,highlight,zone};}
