import {z} from "zod";
import {auditV8RobotDirections,directV8Robot,v8RobotDirectionSchema,type V8AudioFrame,type V8RobotDirection} from "./solomonRobotV8";
import {createSolomonCreatorStoryManifest,type SolomonCaptureApproval,type SolomonStoryAssetId,type SolomonStorySource} from "./solomonCreatorStory";

export const SOLOMON_CREATOR_STORY_V8_ID="solomon-creator-story-v8-robot" as const;
export const SOLOMON_CREATOR_STORY_V8_DURATION_FRAMES=1080 as const;
const HASHES:Record<SolomonStoryAssetId,string>={jobs:"f01434def589919da1b77d1e2a6e57185cdbee43982b1440eb61f5e6122c6704",tracker:"d638462cb696da5d1724413a55baba58f19e4dd55e36fc39cafd461fecc99b8b",contacts:"a36e85e2b24f2a8c66b6b7b11a9f039ffc5a251e838097bf38c5ab4488e5c301",outreach:"9733ef9c20e54f909f4b57f5d41484ad1582dcb18e9680a7c182424d21c61dfc"};

export const v8ClaimSchema=z.object({id:z.string(),clause:z.string(),assetId:z.enum(["jobs","tracker","contacts","outreach"]),sourceSha256:z.string().regex(/^[a-f0-9]{64}$/),verifiedInterval:z.object({startMs:z.number(),endMs:z.number()}),requiredReadableText:z.array(z.string()).min(1),requiredOcrConfidence:z.number().min(0).max(1),phoneProofRegion:z.object({x:z.number(),y:z.number(),width:z.number(),height:z.number()}),actionFrame:z.number().int(),resultFrame:z.number().int(),approved:z.literal(true)}).refine(value=>value.resultFrame>=value.actionFrame,"V8 result must follow its action.");
export type V8CompositionFamily="robot_closeup"|"floating_proof"|"ui_macro"|"contact_evidence"|"editorial_takeover"|"mechanism"|"before_after"|"product_result"|"trust_split"|"cta_closeup";
export interface V8Scene{id:string;from:number;to:number;narration:string;family:V8CompositionFamily;claimIds:string[];assetId?:SolomonStoryAssetId;actionFrame:number;resultFrame:number;semanticEventFrames:number[];robot:V8RobotDirection;audioCue:string;collisionExclusionRegions:Array<{id:string;x:number;y:number;width:number;height:number}>;conceptualDisclosure?:string;}
export interface V8Caption{id:string;from:number;to:number;text:string;kind:"narration"|"editorial";highlight?:string;}
export interface SolomonCreatorStoryV8Manifest{schemaVersion:"8";id:typeof SOLOMON_CREATOR_STORY_V8_ID;canvas:{width:1080;height:1920;fps:30;durationInFrames:1080};distributionObjective:{brand:"Solomon";action:"save";ctaText:"SAVE THIS SOLOMON WORKFLOW";destinationVerified:false;commentDeliveryVerified:false;accountIdentity:"SOLOMON"};script:string;sources:SolomonStorySource[];claims:z.infer<typeof v8ClaimSchema>[];scenes:V8Scene[];captions:V8Caption[];regenerationLineage:{parentVersion:"7";parentManifestSha256:string;reviewRequired:true};release:{generatedMediaPrivate:true;publicReleaseApproved:false};}

export const SOLOMON_CREATOR_STORY_V8_SCRIPT="This job just hit interviewing. And Solomon already found the person who can help next. Normally, you rebuild context across the job post, profile, notes, contacts, and a blank email, copying everything tab to tab. Solomon keeps the role and company attached, then shows why this person matters: target company, hiring relevance, and verified supporting evidence. Watch what happens next. The job connects to the person. The proof follows. That exact context becomes one editable message with a clear specific ask. A generic opener becomes grounded in the real opportunity. Solomon drafts it. You decide. One scattered job search becomes one connected next step: interviewing, relevant person, supporting proof, and an editable message, ready for your review and still under your control. Save this Solomon workflow.";

export function createSolomonCreatorStoryV8Manifest(paths:Record<SolomonStoryAssetId,string>,approval:SolomonCaptureApproval={environment:"authenticated_safe_demo_fixture",publicReleaseApproved:false}):SolomonCreatorStoryV8Manifest{
  const sources=createSolomonCreatorStoryManifest(paths,approval).sources.map(source=>source.id==="outreach"?{...source,privacyMasks:[...source.privacyMasks,{x:.39,y:.13,width:.6,height:.13,label:"PRIVATE RECIPIENT"}]}:source);
  const claims=[claim("status_changed","The job is Interviewing.","tracker",21,36,["Interviewing"],{x:.4,y:.42,width:.27,height:.13}),claim("contact_surfaced","A relevant contact is visible.","contacts",42,60,["Relevant contact"],{x:.02,y:.42,width:.49,height:.19}),claim("contact_reason","Target-company, hiring-relevance, and supporting evidence are visible.","contacts",72,96,["Hiring manager","Direct match","Verified"],{x:.02,y:.42,width:.49,height:.19}),claim("role_company","The role and company remain attached.","jobs",240,270,["Senior Product Engineer","Faire"],{x:.03,y:.07,width:.48,height:.18}),claim("draft_context","The genuine draft contains role and company context.","outreach",510,570,["Senior Product Engineer","Faire"],{x:.4,y:.08,width:.57,height:.42}),claim("draft_control","The genuine message is editable and unsent.","outreach",708,750,["DRAFT — NOT SENT","Edit"],{x:.4,y:.08,width:.57,height:.42})];
  const scenes:V8Scene[]=[
    scene("hook-host",0,21,"This job just hit interviewing.","robot_closeup",[],undefined,0,12,[0,9,18],robot("hook-host",21,"host","forward_lean","alert","camera",.8),"hook_impact",[]),
    scene("status-proof",21,42,"","ui_macro",["status_changed"],"tracker",21,36,[21,30,39],absent("status-proof",21),"status_change",[{id:"status",x:.25,y:.32,width:.5,height:.2}]),
    scene("contact-reveal",42,72,"And Solomon already found the person who can help next.","floating_proof",["contact_surfaced"],"contacts",42,60,[42,51,60,69],robot("contact-reveal",30,"cameo_left","point","surprised","product_right",.5),"contact_reveal",[{id:"contact",x:.28,y:.18,width:.64,height:.46}]),
    scene("contact-evidence",72,102,"","contact_evidence",["contact_reason"],"contacts",72,96,[72,80,88,96],robot("contact-evidence",30,"cameo_right","presentation_palm","focused","product_left",.25),"evidence_attach",[{id:"evidence",x:.08,y:.46,width:.64,height:.21}]),
    scene("problem-recoil",102,126,"Normally, you rebuild context","robot_closeup",[],undefined,102,114,[102,111,120],robot("problem-recoil",24,"host","recoil","concerned","camera",-.7),"problem_turn",[]),
    scene("five-tools",126,240,"across the job post, profile, notes, contacts, and a blank email, copying everything tab to tab.","mechanism",[],undefined,126,222,[126,144,162,180,198,216,234],robot("five-tools",114,"cameo_right","open_palm","concerned","product_left",-.55),"tool_layers",[] ,"CONCEPTUAL CONNECTIVE ANIMATION"),
    scene("role-proof",240,300,"Solomon keeps the role and company attached,","ui_macro",["role_company"],"jobs",240,270,[240,258,276,294],absent("role-proof",60),"role_lock",[{id:"role",x:.08,y:.18,width:.8,height:.3}]),
    scene("reason-proof",300,390,"then shows why this person matters: target company, hiring relevance, and verified supporting evidence.","contact_evidence",["contact_reason"],"contacts",300,348,[300,318,336,354,372,387],robot("reason-proof",90,"cameo_left","point","focused","product_right",.35),"reason_steps",[{id:"reason",x:.32,y:.2,width:.62,height:.47}]),
    scene("signature-mechanism",390,510,"Watch what happens next. The job connects to the person. The proof follows.","mechanism",["role_company","contact_reason"],"outreach",390,486,[390,408,426,444,462,480,498],robot("signature-mechanism",120,"cameo_right","presentation_palm","confident","product_left",.3),"signature_transform",[],"CONCEPTUAL CONNECTIONS BETWEEN VERIFIED PRODUCT EVIDENCE"),
    scene("draft-assembly",510,618,"That exact context becomes one editable message with a clear specific ask.","product_result",["draft_context"],"outreach",510,594,[510,528,546,564,582,600,615],absent("draft-assembly",108),"draft_assembly",[{id:"draft",x:.1,y:.18,width:.8,height:.62}]),
    scene("comparison",618,708,"A generic opener becomes grounded in the real opportunity.","before_after",["draft_context"],"outreach",618,684,[618,636,654,672,690,705],robot("comparison",90,"cameo_right","open_palm","skeptical","product_left",.1),"comparison_change",[]),
    scene("trust",708,780,"Solomon drafts it. You decide.","trust_split",["draft_control"],"outreach",708,750,[708,726,744,762,777],robot("trust",72,"split_left","stop_approval","relieved","product_right",.1),"edit_action",[{id:"edit",x:.5,y:.2,width:.44,height:.58}]),
    scene("payoff",780,966,"One scattered job search becomes one connected next step: interviewing, relevant person, supporting proof, and an editable message, ready for your review and still under your control.","product_result",["status_changed","contact_surfaced","contact_reason","draft_context","draft_control"],"outreach",780,930,[780,804,828,852,876,900,924,948,963],robot("payoff",186,"cameo_left","open_palm","confident","product_right",.25),"payoff_climax",[{id:"result",x:.36,y:.17,width:.58,height:.45}]),
    scene("cta",966,1056,"Save this Solomon workflow.","cta_closeup",[],undefined,966,1020,[966,984,1002,1020,1038,1053],robot("cta",90,"host","save","wink","down_cta",.55),"cta_resolve",[]),
    scene("sting",1056,1080,"","editorial_takeover",[],undefined,1056,1068,[1056,1068,1079],absent("sting",24),"brand_sting",[])
  ];
  const captions:V8Caption[]=[cap("h",0,21,"THIS JOB HIT","narration","HIT"),cap("i",21,42,"INTERVIEWING","editorial"),cap("p",42,72,"THE PERSON","narration","PERSON"),cap("old",126,156,"FIVE TOOLS","editorial"),cap("copy",198,228,"COPY. PASTE. REBUILD.","narration","REBUILD"),cap("why",300,330,"WHY THIS PERSON","narration","WHY"),cap("move",390,420,"WATCH THE CONTEXT MOVE","narration","MOVE"),cap("grounded",654,690,"GROUNDED","editorial"),cap("control",720,756,"YOU DECIDE","narration","YOU"),cap("one",816,858,"ONE CONNECTED NEXT STEP","editorial")];
  const manifest:SolomonCreatorStoryV8Manifest={schemaVersion:"8",id:SOLOMON_CREATOR_STORY_V8_ID,canvas:{width:1080,height:1920,fps:30,durationInFrames:1080},distributionObjective:{brand:"Solomon",action:"save",ctaText:"SAVE THIS SOLOMON WORKFLOW",destinationVerified:false,commentDeliveryVerified:false,accountIdentity:"SOLOMON"},script:SOLOMON_CREATOR_STORY_V8_SCRIPT,sources,claims,scenes,captions,regenerationLineage:{parentVersion:"7",parentManifestSha256:"53edafad7b6ef2855395d894d4c27f8688578750f5395021350546885ae31573",reviewRequired:true},release:{generatedMediaPrivate:true,publicReleaseApproved:false}};assertSolomonCreatorStoryV8Manifest(manifest);return manifest;
}

export function auditSolomonCreatorStoryV8(manifest:SolomonCreatorStoryV8Manifest){const words=manifest.script.match(/[A-Za-z0-9']+/g)?.length??0;const narration=manifest.scenes.map(({narration})=>narration).filter(Boolean).join(" ");const semanticGaps=manifest.scenes.flatMap(scene=>scene.semanticEventFrames.slice(1).map((frame,index)=>({sceneId:scene.id,gap:frame-scene.semanticEventFrames[index]!}))).filter(({gap})=>gap>27);const adjacentFamilies=manifest.scenes.slice(1).flatMap((scene,index)=>scene.family===manifest.scenes[index]!.family?[`${manifest.scenes[index]!.id}->${scene.id}`]:[]);const occupancyWeights:Record<V8CompositionFamily,number>={robot_closeup:0,floating_proof:.65,ui_macro:1,contact_evidence:.6,editorial_takeover:0,mechanism:.45,before_after:.5,product_result:.8,trust_split:.5,cta_closeup:0};const productFrames=manifest.scenes.filter(scene=>scene.assetId).reduce((sum,scene)=>sum+(scene.to-scene.from)*occupancyWeights[scene.family],0);const robot=auditV8RobotDirections(manifest.scenes.map(({robot})=>robot));const passed=narration===manifest.script&&words/(36/60)>=210&&words/(36/60)<=230&&semanticGaps.length===0&&adjacentFamilies.length===0&&productFrames/1080>=.35&&productFrames/1080<=.55&&robot.passed;return{passed,words,wordsPerMinute:words/(36/60),productOccupancy:productFrames/1080,semanticGaps,adjacentFamilies,robot};}
export function assertSolomonCreatorStoryV8Manifest(manifest:SolomonCreatorStoryV8Manifest){z.object({schemaVersion:z.literal("8"),id:z.literal(SOLOMON_CREATOR_STORY_V8_ID),sources:z.array(z.unknown()).length(4),claims:z.array(v8ClaimSchema).min(6),scenes:z.array(z.unknown()).min(14),captions:z.array(z.unknown()).min(8)}).parse(manifest);manifest.scenes.forEach((scene,index)=>{if(scene.from!==(index?manifest.scenes[index-1]!.to:0)||scene.to<=scene.from)throw new Error(`V8 scene ${scene.id} is not contiguous.`);v8RobotDirectionSchema.parse(scene.robot);});if(manifest.scenes.at(-1)?.to!==1080)throw new Error("V8 timeline must end at 1080.");if(manifest.sources.some(source=>source.sourceSha256!==HASHES[source.id]))throw new Error("V8 source hash mismatch.");const audit=auditSolomonCreatorStoryV8(manifest);if(!audit.passed)throw new Error(`V8 contract failed: ${JSON.stringify(audit)}`);}

function claim(id:string,clause:string,assetId:SolomonStoryAssetId,actionFrame:number,resultFrame:number,text:string[],region:{x:number;y:number;width:number;height:number}){const intervals={jobs:{startMs:500,endMs:10000},tracker:{startMs:500,endMs:8600},contacts:{startMs:500,endMs:9800},outreach:{startMs:500,endMs:8900}};return v8ClaimSchema.parse({id,clause,assetId,sourceSha256:HASHES[assetId],verifiedInterval:intervals[assetId],requiredReadableText:text,requiredOcrConfidence:.72,phoneProofRegion:region,actionFrame,resultFrame,approved:true});}
function scene(id:string,from:number,to:number,narration:string,family:V8CompositionFamily,claimIds:string[],assetId:SolomonStoryAssetId|undefined,actionFrame:number,resultFrame:number,semanticEventFrames:number[],robotDirection:V8RobotDirection,audioCue:string,collisionExclusionRegions:V8Scene["collisionExclusionRegions"],conceptualDisclosure?:string):V8Scene{return{id,from,to,narration,family,claimIds,assetId,actionFrame,resultFrame,semanticEventFrames,robot:robotDirection,audioCue,collisionExclusionRegions,conceptualDisclosure};}
function frames(duration:number):V8AudioFrame[]{return Array.from({length:Math.max(2,Math.ceil(duration/3))},(_,index)=>({frame:Math.min(duration-1,index*3),rms:index%5===0?.08:.45+(index%4)*.09,speaking:index%5!==0,onset:index%7===1?.8:.08,phraseBoundary:index%11===0,emphasized:index%9===3,pitchDelta:((index%7)-3)/5}));}
function robot(sceneId:string,duration:number,role:V8RobotDirection["role"],pose:V8RobotDirection["pose"],expression:V8RobotDirection["expression"],gaze:V8RobotDirection["gaze"],lean:number){return directV8Robot({sceneId,role,pose,expression,gaze,gazeArrivalFrame:2,gestureStartFrame:5,gesturePeakFrame:Math.min(duration-4,Math.max(9,Math.round(duration*.45))),recoveryFrame:Math.min(duration-1,Math.max(14,Math.round(duration*.82))),shoulderAsymmetry:sceneId.length%2?.45:-.35,lean,audioFrames:frames(duration)});}
function absent(sceneId:string,duration:number){return directV8Robot({sceneId,role:"absent",pose:"rest",expression:"alert",gaze:"camera",gazeArrivalFrame:0,gestureStartFrame:1,gesturePeakFrame:Math.max(2,Math.floor(duration/2)),recoveryFrame:Math.max(3,duration-1),shoulderAsymmetry:0,lean:0,audioFrames:frames(duration)});}
function cap(id:string,from:number,to:number,text:string,kind:V8Caption["kind"],highlight?:string):V8Caption{return{id,from,to,text,kind,highlight};}
