import { z } from "zod";
import { auditMascotPerformanceV9, auditSolomonMascotV9, SOLOMON_MASCOT_V9_GEOMETRY, v9MascotPerformanceSchema, type V9MascotAudioFrame, type V9MascotFace, type V9MascotGesture, type V9MascotPerformance } from "./solomonMascotV9";
import { auditV9Cta, auditV9Hook, auditV9SemanticMotion, auditV9Transitions, type V9Rect, type V9SemanticEvent } from "./creatorStoryV9Quality";

export const SOLOMON_CREATOR_STORY_V9_ID = "solomon-creator-story-v9-mascot" as const;
export const SOLOMON_CREATOR_STORY_V9_DURATION_FRAMES = 1080 as const;
export const SOLOMON_CREATOR_STORY_V9_SCRIPT = "This job just moved to interviewing. Solomon already found the person who can help next. Normally, that means opening the job post, profile, notes, contacts, and a blank email, then rebuilding the same context five times. Solomon keeps the role and company together. It shows why this person matters: they work at the target company, they are relevant to hiring, and the evidence stays attached. Watch the context move. The job reveals the person. The proof builds one grounded message with a clear ask. Instead of a generic opener, you get language tied to the real opportunity. Solomon drafts it. You edit it. Nothing sends until you decide. One scattered search becomes one connected next step: interviewing, relevant person, supporting proof, and an editable message. Save this for your next job search.";

export type V9AssetId = "jobs" | "tracker" | "contacts" | "outreach";
export type V9Family = "mascot_hook" | "status_action" | "contact_reveal" | "friction" | "five_surfaces" | "role_object" | "reason_steps" | "signature" | "draft_build" | "comparison" | "human_control" | "payoff" | "cta" | "sting";
export interface V9Source { id: V9AssetId; sourcePath: string; sourceSha256: string; sourceWidth: 1440; sourceHeight: 900; verifiedInterval: { startMs: number; endMs: number }; environment: "fail_closed_synthetic_solomon_demo"; receipt: string; privacyMasks: [] }
export interface V9Claim { id: string; clause: string; assetId: V9AssetId; sourceSha256: string; requiredReadableText: string[]; actionFrame: number; resultFrame: number; approved: true }
export interface V9Scene { id: string; from: number; to: number; narration: string; family: V9Family; assetId?: V9AssetId; claimIds: string[]; semanticEvents: V9SemanticEvent[]; transition: { type: "cut" | "slide" | "match_cut" | "object_wipe" | "dissolve"; purpose: string }; mascot: V9MascotPerformance; layout: V9Rect[]; productFocus?: { x: number; y: number; zoom: number; trim: number }; conceptualDisclosure?: string }
export interface V9Caption { id: string; from: number; to: number; text: string; beatText: string; highlight?: string; zone: "top" | "bottom" }
export interface SolomonCreatorStoryV9Manifest { schemaVersion: "9"; id: typeof SOLOMON_CREATOR_STORY_V9_ID; canvas: { width: 1080; height: 1920; fps: 30; durationInFrames: 1080 }; distributionObjective: { brand: "Solomon"; action: "save"; ctaText: "SAVE THIS FOR YOUR NEXT JOB SEARCH"; destinationVerified: false; commentDeliveryVerified: false; accountIdentity: "SOLOMON" }; script: string; sources: V9Source[]; claims: V9Claim[]; scenes: V9Scene[]; captions: V9Caption[]; mascotGeometry: typeof SOLOMON_MASCOT_V9_GEOMETRY; selectedMascotCandidate: "code-glossy-arched-smile-a"; regenerationLineage: { parentVersion: "8"; parentMasterSha256: string; reviewRequired: true }; release: { generatedMediaPrivate: true; publicReleaseApproved: false } }

const HASHES: Record<V9AssetId, string> = {
  jobs: "bceeab767260fe2c3adbd88e6de8041cd520ebff7962c79f69adc86c7f32c7e9",
  tracker: "6dc4367827e5d1faeccbf7e7a75589595d0ab1f2416c734e2cd4ddc607601e8e",
  contacts: "4b8784ac6b4ccf4b30cf525f954ae37f16ac87cc09f8ed131c13e09216a49e15",
  outreach: "80d9ba804379ae51101b26c09bae2907d0fd49b7dae5fa74766a4b0e100379ea"
};

export function createSolomonCreatorStoryV9Manifest(paths: Record<V9AssetId, string>): SolomonCreatorStoryV9Manifest {
  const sources = (Object.keys(paths) as V9AssetId[]).map((id): V9Source => ({ id, sourcePath: paths[id], sourceSha256: HASHES[id], sourceWidth: 1440, sourceHeight: 900, verifiedInterval: { startMs: 0, endMs: 6000 }, environment: "fail_closed_synthetic_solomon_demo", receipt: "solomon-demo-mode@8f71348b; external providers disabled; synthetic identities only", privacyMasks: [] }));
  const claims: V9Claim[] = [
    claim("role_company", "The role and company remain attached.", "jobs", ["Product Engineer", "Northstar Labs"], 219, 250),
    claim("status", "The job moved to Interviewing.", "tracker", ["Product Engineer", "Interviewing"], 21, 37),
    claim("person", "A relevant fictional contact is visible.", "contacts", ["Avery Chen", "Senior Technical Recruiter", "Northstar Labs"], 42, 60),
    claim("proof", "The fictional contact includes supporting proof.", "contacts", ["Recruiting title at the target company", "Synthetic fixture; not a real person"], 279, 338),
    claim("draft", "A complete editable unsent draft is visible.", "outreach", ["Avery Chen", "synthetic, unsent demo draft", "Save Edit"], 489, 540),
    claim("control", "The draft remains under user control.", "outreach", ["Save Edit", "Cancel", "review and send it manually"], 690, 720)
  ];
  const scenes: V9Scene[] = [
    scene("hook", 0, 21, "This job just moved to interviewing.", "mascot_hook", undefined, [], mascot("hook",21,"host","wide_surprise","point_down","open_palm","camera", "hook-line"), [[0,"lean toward camera"],[9,"eyes widen"],[18,"point lands"]], "cut", layouts("host")),
    scene("status", 21, 42, "", "status_action", "tracker", ["status"], mascot("status",21,"cameo_left","happy_crescent","presentation_palm","point_right","product","interviewing-card"), [[21,"cursor enters"],[30,"stage clicks"],[39,"confirmation lands"]], "match_cut", layouts("left"), {x:.5,y:.46,zoom:1.25,trim:1.1}),
    scene("contact", 42, 96, "Solomon already found the person who can help next.", "contact_reveal", "contacts", ["person"], mascot("contact",54,"cameo_left","happy_crescent","open_palm","point_right","product","avery-card"), [[42,"contact card rises"],[55,"name locks"],[69,"role appears"],[84,"company proof attaches"]], "slide", layouts("left"), {x:.25,y:.56,zoom:1.55,trim:1.0}),
    scene("old-way",96,120,"Normally, that means opening","friction",undefined,[],mascot("old-way",24,"host","concerned","stop_control","open_palm","camera","first-window"),[[96,"peach world cuts in"],[108,"first window hits"],[117,"mascot recoils"]],"cut",layouts("host"),undefined,"CONCEPTUAL FRICTION ANIMATION"),
    scene("five-surfaces",120,219,"the job post, profile, notes, contacts, and a blank email, then rebuilding the same context five times.","five_surfaces",undefined,[],mascot("five-surfaces",99,"cameo_right","old_way_lidded","open_palm","stop_control","product","surface-stack"),[[120,"job opens"],[138,"profile arrives"],[156,"notes copy"],[174,"contacts stack"],[192,"email opens"],[210,"stack collapses"]],"object_wipe",layouts("right"),undefined,"CONCEPTUAL FRICTION ANIMATION"),
    scene("role",219,279,"Solomon keeps the role and company together.","role_object","jobs",["role_company"],mascot("role",60,"cameo_right","focused","point_left","presentation_palm","product","role-company"),[[219,"real UI lands"],[237,"role extracts"],[255,"company joins"],[273,"object carries"]],"match_cut",layouts("right"),{x:.22,y:.2,zoom:1.55,trim:.8}),
    scene("reason",279,369,"It shows why this person matters: they work at the target company, they are relevant to hiring, and the evidence stays attached.","reason_steps","contacts",["person","proof"],mascot("reason",90,"cameo_left","focused","presentation_palm","point_right","product","proof-lines"),[[279,"contact anchors"],[297,"company proof"],[315,"hiring relevance"],[333,"source proof"],[351,"proof locks"]],"slide",layouts("left"),{x:.23,y:.59,zoom:1.55,trim:1.2}),
    scene("signature",369,489,"Watch the context move. The job reveals the person. The proof builds one grounded message with a clear ask.","signature","outreach",["role_company","person","proof","draft"],mascot("signature",120,"cameo_right","happy_crescent","presentation_palm","point_left","product","context-token"),[[369,"job token enters"],[390,"person revealed"],[411,"proof attaches"],[432,"message opens"],[453,"context travels"],[474,"ask resolves"]],"object_wipe",layouts("right"),{x:.62,y:.35,zoom:1.28,trim:1.0},"CONCEPTUAL CONNECTIONS BETWEEN VERIFIED PRODUCT EVIDENCE"),
    scene("draft",489,609,"Instead of a generic opener, you get language tied to the real opportunity.","draft_build","outreach",["draft"],mascot("draft",120,"cameo_left","focused","point_right","approval","product","draft-editor"),[[489,"blank editor opens"],[510,"role inserts"],[531,"company inserts"],[552,"reason inserts"],[573,"ask inserts"],[594,"message completes"]],"cut",layouts("left"),{x:.62,y:.36,zoom:1.32,trim:1.2}),
    scene("grounded",609,690,"","comparison","outreach",["draft"],mascot("grounded",81,"cameo_right","happy_crescent","stop_control","approval","product","grounded-line"),[[609,"generic line visible"],[630,"line replaces"],[651,"context highlight"],[672,"approval lands"]],"match_cut",layouts("right"),{x:.62,y:.4,zoom:1.34,trim:1.5}),
    scene("control",690,744,"Solomon drafts it. You edit it. Nothing sends until you decide.","human_control","outreach",["control"],mascot("control",54,"split_left","direct_cta","open_palm","stop_control","product","save-edit-controls"),[[690,"cursor enters"],[708,"word edits"],[726,"unsent control holds"],[741,"open palm resolves"]],"cut",layouts("left"),{x:.62,y:.58,zoom:1.22,trim:2.0}),
    scene("payoff",744,945,"One scattered search becomes one connected next step: interviewing, relevant person, supporting proof, and an editable message.","payoff","outreach",["status","person","proof","draft","control"],mascot("payoff",201,"cameo_right","happy_crescent","celebration","approval","product","complete-result"),[[744,"fragments flash"],[765,"result takes over"],[792,"interviewing lands"],[819,"person lands"],[846,"proof lands"],[873,"draft lands"],[900,"edit control lands"],[927,"mascot celebrates"]],"match_cut",layouts("right"),{x:.62,y:.58,zoom:1.2,trim:1.0}),
    scene("cta",945,1056,"Save this for your next job search.","cta",undefined,[],mascot("cta",111,"host","direct_cta","save_bookmark","point_right","cta","bookmark"),[[945,"direct gaze"],[966,"bookmark enters"],[987,"gaze shifts"],[1008,"save points"],[1029,"gaze returns"],[1050,"wink"]],"cut",layouts("host")),
    scene("sting",1056,1080,"","sting",undefined,[],mascot("sting",24,"cameo_right","wink","wave","rest_mitt","camera","solomon-mark"),[[1056,"symbol enters"],[1068,"bobble chimes"],[1079,"final pose"]],"cut",layouts("right"))
  ];
  const captions: V9Caption[] = [
    cap("hook",0,21,"THIS JOB JUST MOVED TO INTERVIEWING.","This job just moved to interviewing.","INTERVIEWING","top"), cap("person",42,74,"THE PERSON WHO HELPS NEXT","Solomon already found the person who can help next.","PERSON","top"), cap("five",120,154,"FIVE SURFACES","the job post, profile, notes, contacts, and a blank email","FIVE","top"), cap("together",219,260,"ROLE + COMPANY, TOGETHER","Solomon keeps the role and company together.","TOGETHER","top"), cap("why",279,315,"WHY THIS PERSON","It shows why this person matters","WHY","top"), cap("move",369,408,"WATCH THE CONTEXT MOVE","Watch the context move.","MOVE","top"), cap("grounded",630,675,"GENERIC → GROUNDED","Instead of a generic opener, you get language tied to the real opportunity.","GROUNDED","top"), cap("control",690,735,"YOU EDIT. YOU DECIDE.","You edit it. Nothing sends until you decide.","YOU","top"), cap("one",765,825,"ONE CONNECTED NEXT STEP","One scattered search becomes one connected next step","ONE","top"), cap("cta",945,1056,"SAVE THIS FOR YOUR NEXT JOB SEARCH","Save this for your next job search.","SAVE","bottom")
  ];
  const manifest: SolomonCreatorStoryV9Manifest = { schemaVersion:"9", id:SOLOMON_CREATOR_STORY_V9_ID, canvas:{width:1080,height:1920,fps:30,durationInFrames:1080}, distributionObjective:{brand:"Solomon",action:"save",ctaText:"SAVE THIS FOR YOUR NEXT JOB SEARCH",destinationVerified:false,commentDeliveryVerified:false,accountIdentity:"SOLOMON"}, script:SOLOMON_CREATOR_STORY_V9_SCRIPT, sources, claims, scenes, captions, mascotGeometry:SOLOMON_MASCOT_V9_GEOMETRY, selectedMascotCandidate:"code-glossy-arched-smile-a", regenerationLineage:{parentVersion:"8",parentMasterSha256:"11f51d350699f10b9e653607346e64b786e8650dbe1c195770179c4d1eafb150",reviewRequired:true}, release:{generatedMediaPrivate:true,publicReleaseApproved:false} };
  assertSolomonCreatorStoryV9Manifest(manifest);
  return manifest;
}

export function auditSolomonCreatorStoryV9(manifest: SolomonCreatorStoryV9Manifest) {
  const narration = manifest.scenes.map(({narration}) => narration).filter(Boolean).join(" ");
  const words = manifest.script.match(/[A-Za-z0-9']+/g)?.length ?? 0;
  const semantic = manifest.scenes.map((scene) => ({ sceneId:scene.id, ...auditV9SemanticMotion(scene.semanticEvents, scene.from, scene.to, 27) }));
  const transitions = auditV9Transitions(manifest.scenes.slice(1).map(({transition}) => transition));
  const mascotGeometry = auditSolomonMascotV9(manifest.mascotGeometry);
  const mascotPerformance = auditMascotPerformanceV9(manifest.scenes.map(({mascot}) => mascot));
  const hook = auditV9Hook(manifest.scenes[0]!.narration, manifest.captions[0]!.text);
  const cta = auditV9Cta({...manifest.distributionObjective,text:manifest.distributionObjective.ctaText});
  const productFrames = manifest.scenes.filter(({assetId}) => assetId).reduce((sum, scene) => sum + scene.to - scene.from, 0);
  const passed = narration === manifest.script && words === 132 && semantic.every(({passed}) => passed) && transitions.passed && mascotGeometry.passed && mascotPerformance.passed && hook.passed && cta.passed && productFrames / 1080 >= .35 && productFrames / 1080 <= .8;
  return { passed, narrationExact: narration === manifest.script, words, wordsPerMinute: words / .6, semantic, transitions, mascotGeometry, mascotPerformance, hook, cta, productOccupancy: productFrames/1080 };
}

export function assertSolomonCreatorStoryV9Manifest(manifest: SolomonCreatorStoryV9Manifest) {
  z.object({schemaVersion:z.literal("9"),id:z.literal(SOLOMON_CREATOR_STORY_V9_ID),sources:z.array(z.unknown()).length(4),claims:z.array(z.unknown()).min(6),scenes:z.array(z.unknown()).length(14),captions:z.array(z.unknown()).min(10)}).parse(manifest);
  manifest.scenes.forEach((scene,index) => { if (scene.from !== (index ? manifest.scenes[index-1]!.to : 0) || scene.to <= scene.from) throw new Error(`V9 scene ${scene.id} is not contiguous.`); v9MascotPerformanceSchema.parse(scene.mascot); });
  if (manifest.scenes.at(-1)?.to !== 1080) throw new Error("V9 timeline must end at frame 1080.");
  if (manifest.sources.some((source) => source.sourceSha256 !== HASHES[source.id])) throw new Error("V9 source hash mismatch.");
  const audit = auditSolomonCreatorStoryV9(manifest); if (!audit.passed) throw new Error(`V9 contract failed: ${JSON.stringify(audit)}`);
}

function claim(id:string,clause:string,assetId:V9AssetId,requiredReadableText:string[],actionFrame:number,resultFrame:number):V9Claim{return{id,clause,assetId,sourceSha256:HASHES[assetId],requiredReadableText,actionFrame,resultFrame,approved:true};}
function scene(id:string,from:number,to:number,narration:string,family:V9Family,assetId:V9AssetId|undefined,claimIds:string[],mascotPlan:V9MascotPerformance,events:Array<[number,string]>,transition:V9Scene["transition"]["type"],layout:V9Rect[],productFocus?:V9Scene["productFocus"],conceptualDisclosure?:string):V9Scene{return{id,from,to,narration,family,assetId,claimIds,mascot:mascotPlan,semanticEvents:events.map(([frame,description])=>({frame,kind:"semantic",description})),transition:{type:transition,purpose:`Advance ${id} story beat`},layout,productFocus,conceptualDisclosure};}
function mascot(sceneId:string,duration:number,role:V9MascotPerformance["role"],emotion:V9MascotFace,leftGesture:V9MascotGesture,rightGesture:V9MascotGesture,gaze:V9MascotPerformance["gazePath"][number]["target"],elementId:string):V9MascotPerformance{return v9MascotPerformanceSchema.parse({sceneId,role,emotion,gazePath:[{frame:0,target:"camera"},{frame:3,target:gaze}],torso:{lean:.25,rotate:sceneId.length%2?.12:-.1,shiftX:0,shiftY:0},head:{tilt:sceneId.length%2?.15:-.12,turn:gaze==="product"?.3:0,beats:[4,Math.max(8,Math.floor(duration*.55))]},leftGesture,rightGesture,gazeArrivalFrame:3,gestureStartFrame:5,gesturePeakFrame:Math.min(duration-5,Math.max(10,Math.floor(duration*.45))),recoveryFrame:Math.min(duration-1,Math.max(15,Math.floor(duration*.85))),interactionTarget:{elementId,x:gaze==="cta"?.72:.62,y:gaze==="cta"?.68:.48,action:`${leftGesture}/${rightGesture}`},audioFrames:audioFrames(duration),skin:"solomon_s",material:"code_glossy"});}
function audioFrames(duration:number):V9MascotAudioFrame[]{return Array.from({length:duration},(_,frame)=>({frame,rms:frame%7===0?.12:.48,speaking:true,onset:frame%13===2?.72:.08,phraseBoundary:frame%29===0,emphasized:frame%23===5,pitchDelta:0,mouth:frame%9<3?"smile_small":frame%9<6?"smile_medium":"smile_emphasis"}));}
function layouts(role:"host"|"left"|"right"):V9Rect[]{const robot=role==="host"?{id:"robot",kind:"robot" as const,left:.2,top:.25,right:.8,bottom:.79}:role==="left"?{id:"robot",kind:"robot" as const,left:0,top:.67,right:.36,bottom:.98}:{id:"robot",kind:"robot" as const,left:.64,top:.67,right:1,bottom:.98},caption={id:"caption-zone",kind:"caption" as const,left:.04,top:.05,right:.96,bottom:.2};if(role==="host")return[robot,caption];return[robot,caption,{id:"product-proof",kind:"product_ocr",left:role==="left"?.4:.05,top:.22,right:role==="right"?.6:.96,bottom:.64}];}
function cap(id:string,from:number,to:number,text:string,beatText:string,highlight:string,zone:V9Caption["zone"]):V9Caption{return{id,from,to,text,beatText,highlight,zone};}
