import { z } from "zod";
import { auditV11BannedStrings, auditV11Captions, auditV11CompositionSimilarity, auditV11Cta, auditV11Hook, auditV11Layout, auditV11NumeralAnchors, auditV11PhoneScale, auditV11RenderedBounds, auditV11SemanticMotion, auditV11StoryConsistency, auditV11Transitions, type V11CompositionFingerprint, type V11Rect, type V11SemanticEvent } from "./creatorStoryV11Quality";
import { compileSolomonCreatorStoryV11, type V11BeatHeadline, type V11CompiledCaption, type V11NumeralAnchor } from "./solomonCreatorStoryV11Beats";
import { compileSolomonV11DemoContent, SOLOMON_V11_DISCLOSURE, type SolomonV11DemoContent } from "./solomonDemoContentV11";
import { auditMascotPerformanceV11, SOLOMON_MASCOT_V11_GEOMETRY, v11MascotPerformanceSchema, type V11Face, type V11Gesture, type V11MascotPerformance, type V11Mouth } from "./solomonMascotV11";

const compiled=compileSolomonCreatorStoryV11();
export const SOLOMON_CREATOR_STORY_V11_ID="solomon-creator-story-v11-performance" as const;
export const SOLOMON_CREATOR_STORY_V11_DURATION_FRAMES=1080 as const;
export const SOLOMON_CREATOR_STORY_V11_HOOK:string=compiled.hook;
export const SOLOMON_CREATOR_STORY_V11_CTA:string=compiled.ctaDisplay;
export const SOLOMON_CREATOR_STORY_V11_CTA_SPOKEN:string=compiled.ctaSpoken;
export const SOLOMON_CREATOR_STORY_V11_CTA_KEYWORD:string=compiled.ctaKeyword;
export const SOLOMON_CREATOR_STORY_V11_SCRIPT:string=compiled.script;
export const SOLOMON_CREATOR_STORY_V11_TTS_BEATS=compiled.ttsBeats;
export const SOLOMON_CREATOR_STORY_V11_HEADLINES:Record<string,V11BeatHeadline>=compiled.headlines;
export const SOLOMON_CREATOR_STORY_V11_NUMERAL_ANCHORS:V11NumeralAnchor[]=compiled.numeralAnchors;

export type V11AssetId="tracker_before"|"tracker_after"|"opportunity"|"contact"|"outreach_blank"|"outreach_complete";
export type V11Family="hook"|"status"|"contact"|"reasons"|"friction"|"five_surfaces"|"collapse"|"role"|"signature"|"draft"|"grounded"|"control"|"payoff"|"result"|"cta"|"sting";
export interface V11DomEvidence { elementId:string; role:string; text:string; box:{x:number;y:number;width:number;height:number}; beforeState?:string; afterState?:string; click?:{x:number;y:number} }
export interface V11Source { id:V11AssetId; sourcePath:string; sourceSha256:string; sourceWidth:1440; sourceHeight:900; verifiedInterval:{startMs:number;endMs:number}; environment:"fail_closed_fictional_solomon_v11"; disclosure:typeof SOLOMON_V11_DISCLOSURE; domEvidence:V11DomEvidence[]; privacyMasks:[] }
export interface V11Claim { id:string; clause:string; assetIds:V11AssetId[]; requiredReadableText:string[]; actionFrame:number; resultFrame:number; approved:true }
export interface V11Scene { id:string; from:number; to:number; narration:string; family:V11Family; assetIds:V11AssetId[]; claimIds:string[]; semanticEvents:V11SemanticEvent[]; transition:{type:"cut"|"slide"|"match_cut"|"object_wipe"|"dissolve";purpose:string}; mascot:V11MascotPerformance; layout:V11Rect[]; camera:{recipe:string;scaleFrom:number;scaleTo:number;focus:{x:number;y:number};semanticTarget:string}; proofRecipe:string; typography:"spoken"|"editorial_peak"|"product_annotation"|"cta"; conceptual:boolean }
export type V11Caption = V11CompiledCaption;
export interface V11CreativeDirector { version:"v11.1"; primaryPromise:string; hook:string; problem:string; mechanism:"JOB → PERSON → PROOF → MESSAGE"; payoff:"ONE CONNECTED NEXT STEP"; trustBoundary:"NOTHING SENDS WITHOUT YOU"; cta:string; emotionalArc:["surprise","frustration","clarity","proof","confidence","control","payoff","direct_action"] }
export interface V11SourceInput { id:V11AssetId; path:string; sha256:string; domEvidence:V11DomEvidence[] }
export interface SolomonCreatorStoryV11Manifest { schemaVersion:"11";id:typeof SOLOMON_CREATOR_STORY_V11_ID;canvas:{width:1080;height:1920;fps:30;durationInFrames:1080};creativeDirector:V11CreativeDirector;distributionObjective:{brand:"Solomon";action:"comment";ctaText:string;ctaSpoken:string;ctaKeyword:string;destinationVerified:false;commentDeliveryVerified:false;accountIdentity:"SOLOMON"};script:string;headlines:Record<string,V11BeatHeadline>;numeralAnchors:V11NumeralAnchor[];demoContent:SolomonV11DemoContent;sources:V11Source[];claims:V11Claim[];scenes:V11Scene[];captions:V11Caption[];mascotGeometry:typeof SOLOMON_MASCOT_V11_GEOMETRY;regenerationLineage:{parentVersion:"10";parentMasterSha256:string;reviewRequired:true};release:{generatedMediaPrivate:true;publicReleaseApproved:false;humanConfirmations:string[]} }

export function createSolomonCreatorStoryV11Manifest(inputs:V11SourceInput[],parentMasterSha256:string):SolomonCreatorStoryV11Manifest{
  const demoContent=compileSolomonV11DemoContent();
  // Fresh compile per manifest: caption/headline/anchor objects must never be
  // shared across manifests, or a mutation in one leaks into the next.
  const freshCompiled=compileSolomonCreatorStoryV11();
  const narr=(id:string)=>freshCompiled.narrationBySceneId[id]??"";
  const sources=inputs.map((input):V11Source=>({id:input.id,sourcePath:input.path,sourceSha256:input.sha256,sourceWidth:1440,sourceHeight:900,verifiedInterval:{startMs:0,endMs:7000},environment:"fail_closed_fictional_solomon_v11",disclosure:SOLOMON_V11_DISCLOSURE,domEvidence:input.domEvidence,privacyMasks:[]}));
  const claims:V11Claim[]=[
    claim("status","The opportunity visibly changes from Applied to Interviewing.",["tracker_before","tracker_after"],["Product Engineer","Applied","Interviewing"],24,50),
    claim("contact","A relevant fictional contact is visible.",["contact"],["Avery Chen","Senior Technical Recruiter","Northstar Labs"],54,88),
    claim("relevance","Three reasons support contact relevance.",["contact"],[...demoContent.contact.reasons],102,126),
    claim("role","The role and company stay connected.",["opportunity"],["Product Engineer","Northstar Labs"],291,338),
    claim("draft","A grounded editable message is readable.",["outreach_complete"],["Product Engineer","Northstar Labs","technical hiring","Save Edit"],585,628),
    claim("control","The message remains unsent and user-controlled.",["outreach_complete"],["Save Edit","Cancel","Nothing sends without you"],735,802)
  ];
  const scenes:V11Scene[]=[
    scene("hook",0,24,narr("hook"),"hook",[],[],mascot("hook",24,"hero_close","happy","wide_open","wave","open_palm","camera","hook-status","emotion",[{atFrame:2,face:"surprised",holdFrames:9}]),"cut","Face-first greeting with a brief surprise accent","spoken",false,layouts("hero"),{recipe:"camera_push",scaleFrom:1.14,scaleTo:1.28,focus:{x:.5,y:.34},semanticTarget:"eyes"}),
    scene("status",24,54,"","status",["tracker_before","tracker_after"],["status"],mascot("status",30,"cameo_left","happy","small_open","presentation_palm","true_point_right","product","interview-control","attention"),"match_cut","Applied → click → Interviewing","product_annotation",false,layouts("left"),{recipe:"control_to_result",scaleFrom:1.7,scaleTo:2.05,focus:{x:.76,y:.62},semanticTarget:"Interviewing"}),
    scene("contact",54,102,"","contact",["contact"],["contact"],mascot("contact",48,"cameo_left","friendly","small_open","open_palm","true_point_right","product","avery-card","attention"),"slide","Opportunity indicator becomes contact card","product_annotation",false,layouts("left"),{recipe:"card_extract",scaleFrom:1.5,scaleTo:1.85,focus:{x:.28,y:.67},semanticTarget:"Avery Chen"}),
    scene("reasons",102,132,"","reasons",["contact"],["relevance"],mascot("reasons",30,"cameo_right","focused","neutral_dash","true_point_left","presentation_palm","product","reasons","interpretation"),"cut","Three evidence cards expand from product","product_annotation",false,layouts("right"),{recipe:"evidence_steps",scaleFrom:1.65,scaleTo:1.95,focus:{x:.27,y:.76},semanticTarget:"relevance proof"}),
    scene("friction",132,162,narr("friction"),"friction",[],[],mascot("friction",30,"host","concerned","concerned_curve","stop_palm","open_palm","camera","crowding-tabs","emotion"),"cut","Tabs crowd and recoil the presenter","editorial_peak",true,layouts("host"),{recipe:"recoil",scaleFrom:1,scaleTo:1.06,focus:{x:.5,y:.45},semanticTarget:"mascot"}),
    scene("five",162,252,narr("five"),"five_surfaces",["opportunity","contact","outreach_blank"],[],mascot("five",90,"cameo_right","skeptical","neutral_dash","thinking_hand","stop_palm","product","five-surfaces","interpretation"),"object_wipe","Five realistic tools copy one role","editorial_peak",true,layouts("right"),{recipe:"copy_chain",scaleFrom:1.05,scaleTo:1.32,focus:{x:.48,y:.47},semanticTarget:"5× context"}),
    scene("collapse",252,291,"","collapse",["opportunity"],[],mascot("collapse",39,"cameo_right","focused","small_open","presentation_palm","approval","product","opportunity-card","transition"),"object_wipe","Five fragments collapse into opportunity","editorial_peak",true,layouts("right"),{recipe:"fragments_to_object",scaleFrom:.9,scaleTo:1.25,focus:{x:.5,y:.48},semanticTarget:"opportunity"}),
    scene("role",291,354,narr("role"),"role",["opportunity","contact"],["role"],mascot("role",63,"cameo_right","focused","small_open","true_point_left","presentation_palm","product","role-company","attention"),"match_cut","Opportunity object carries into evidence","product_annotation",false,layouts("right"),{recipe:"object_follow",scaleFrom:1.42,scaleTo:1.7,focus:{x:.25,y:.3},semanticTarget:"Product Engineer at Northstar Labs"}),
    scene("reason",354,420,narr("reason"),"reasons",["contact"],["contact","relevance"],mascot("reason",66,"cameo_left","focused","small_open","presentation_palm","true_point_right","product","avery-proof","interpretation"),"cut","Contact and proof become one object","product_annotation",false,layouts("left"),{recipe:"proof_attach",scaleFrom:1.55,scaleTo:1.92,focus:{x:.25,y:.7},semanticTarget:"Avery evidence"}),
    scene("signature",420,585,narr("signature"),"signature",["opportunity","contact","outreach_blank","outreach_complete"],["role","contact","relevance","draft"],mascot("signature",165,"cameo_right","happy","confident_smile","presentation_palm","true_point_left","product","context-flow","transition"),"object_wipe","JOB → PERSON → PROOF → MESSAGE transformation","editorial_peak",true,layouts("right"),{recipe:"semantic_follow",scaleFrom:1,scaleTo:1.3,focus:{x:.52,y:.48},semanticTarget:"moving context"}),
    scene("draft",585,645,"","draft",["outreach_blank","outreach_complete"],["draft"],mascot("draft",60,"absent","focused","neutral_dash","rest_mitt","rest_mitt","product","draft-line","none"),"cut","Blank editor becomes grounded sentence","product_annotation",false,layouts("product"),{recipe:"sentence_build",scaleFrom:1.65,scaleTo:2.05,focus:{x:.63,y:.47},semanticTarget:"grounded sentence"}),
    scene("grounded",645,735,narr("grounded"),"grounded",["outreach_blank","outreach_complete"],["draft"],mascot("grounded",90,"cameo_right","skeptical","confident_smile","stop_palm","approval","product","sentence-compare","interpretation"),"match_cut","Generic sentence morphs into grounded sentence","editorial_peak",false,layouts("right"),{recipe:"text_morph",scaleFrom:1.7,scaleTo:2.08,focus:{x:.61,y:.47},semanticTarget:"inserted context"}),
    scene("control",735,825,narr("control"),"control",["outreach_complete"],["control"],mascot("control",90,"cameo_left","direct_cta","neutral_dash","stop_palm","true_point_right","product","save-edit","interpretation"),"cut","Edit one word, click Save Edit, leave send untouched","product_annotation",false,layouts("left"),{recipe:"edit_then_hold",scaleFrom:1.7,scaleTo:2.0,focus:{x:.62,y:.66},semanticTarget:"Save Edit and Cancel"}),
    scene("payoff",825,930,narr("payoff"),"payoff",["tracker_after","opportunity","contact","outreach_complete"],["status","role","contact","relevance","draft","control"],mascot("payoff",105,"absent","happy","closed_smile","rest_mitt","rest_mitt","product","connected-result","none"),"object_wipe","Disconnected surfaces collapse into one combined proof state","editorial_peak",true,layouts("product"),{recipe:"before_after_collapse",scaleFrom:.82,scaleTo:1.16,focus:{x:.5,y:.48},semanticTarget:"combined result"}),
    scene("result",930,960,"","result",["tracker_after","contact","outreach_complete"],["status","contact","relevance","draft"],mascot("result",30,"cameo_right","happy","wide_open","celebration","approval","product","connected-result","payoff_reaction"),"cut","Result holds while mascot celebrates after proof","editorial_peak",false,layouts("right"),{recipe:"result_reframe",scaleFrom:1.08,scaleTo:1.28,focus:{x:.5,y:.42},semanticTarget:"one connected next step"}),
    scene("cta",960,1056,narr("cta"),"cta",[],[],mascot("cta",96,"host","direct_cta","confident_smile","presentation_palm","wave","cta","comment-keyword","cta"),"cut","Look, present keyword, wave, confirm, return gaze, wink","cta",false,layouts("host"),{recipe:"comment_performance",scaleFrom:1.08,scaleTo:1.18,focus:{x:.5,y:.42},semanticTarget:"comment keyword"}),
    scene("sting",1056,1080,"","sting",[],[],mascot("sting",24,"cameo_right","wink","closed_smile","wave","rest_mitt","camera","solomon-mark","cta"),"match_cut","Bookmark pulse resolves into Solomon mark","cta",false,layouts("right"),{recipe:"pulse_to_mark",scaleFrom:1,scaleTo:1.06,focus:{x:.5,y:.5},semanticTarget:"Solomon"})
  ];
  const captions:V11Caption[]=freshCompiled.captions;
  const creativeDirector:V11CreativeDirector={version:"v11.1",primaryPromise:"Turn one job opportunity into one evidence-grounded next step.",hook:SOLOMON_CREATOR_STORY_V11_HOOK,problem:"Rebuilding the same job context across five disconnected tools.",mechanism:"JOB → PERSON → PROOF → MESSAGE",payoff:"ONE CONNECTED NEXT STEP",trustBoundary:"NOTHING SENDS WITHOUT YOU",cta:SOLOMON_CREATOR_STORY_V11_CTA,emotionalArc:["surprise","frustration","clarity","proof","confidence","control","payoff","direct_action"]};
  const manifest:SolomonCreatorStoryV11Manifest={schemaVersion:"11",id:SOLOMON_CREATOR_STORY_V11_ID,canvas:{width:1080,height:1920,fps:30,durationInFrames:1080},creativeDirector,distributionObjective:{brand:"Solomon",action:"comment",ctaText:SOLOMON_CREATOR_STORY_V11_CTA,ctaSpoken:SOLOMON_CREATOR_STORY_V11_CTA_SPOKEN,ctaKeyword:SOLOMON_CREATOR_STORY_V11_CTA_KEYWORD,destinationVerified:false,commentDeliveryVerified:false,accountIdentity:"SOLOMON"},script:SOLOMON_CREATOR_STORY_V11_SCRIPT,headlines:freshCompiled.headlines,numeralAnchors:freshCompiled.numeralAnchors,demoContent,sources,claims,scenes,captions,mascotGeometry:SOLOMON_MASCOT_V11_GEOMETRY,regenerationLineage:{parentVersion:"10",parentMasterSha256,reviewRequired:true},release:{generatedMediaPrivate:true,publicReleaseApproved:false,humanConfirmations:["mascot appeal and brand fit","voice naturalness and emotional performance","grounded fictional message quality","physical-phone readability","proof credibility","disclosure clarity","CTA appropriateness","Solomon brand/legal approval","demo-footage publication permission","synthetic-presenter disclosure policy","overall reference-quality judgment"]}};
  assertSolomonCreatorStoryV11Manifest(manifest);return manifest;
}

export function auditSolomonCreatorStoryV11(manifest:SolomonCreatorStoryV11Manifest){
  const narration=manifest.scenes.map(({narration})=>narration).filter(Boolean).join(" "),words=manifest.script.match(/[A-Za-z0-9]+(?:[’'-][A-Za-z0-9]+)*/g)?.length??0,wpm=words/(1080/30/60);
  const semantic=manifest.scenes.map((scene)=>({sceneId:scene.id,...auditV11SemanticMotion(scene.semanticEvents,scene.from,scene.to)}));
  const transitions=auditV11Transitions(manifest.scenes.slice(1).map(({transition})=>transition));
  const mascot=auditMascotPerformanceV11(manifest.scenes.map(({mascot})=>mascot));
  const hook=auditV11Hook(manifest.creativeDirector.hook,manifest.headlines["hook"]),cta=auditV11Cta({...manifest.distributionObjective,text:manifest.distributionObjective.ctaText,spoken:manifest.distributionObjective.ctaSpoken,keyword:manifest.distributionObjective.ctaKeyword});
  const captionLints=auditV11Captions(manifest.captions),numeralAnchors=auditV11NumeralAnchors(manifest.numeralAnchors,manifest.script,manifest.headlines);
  const bounds=auditV11RenderedBounds(manifest.scenes.map((scene)=>({id:scene.id,layout:scene.layout,camera:scene.camera,mascotRole:scene.mascot.role})));
  const story=auditV11StoryConsistency({previousStage:manifest.demoContent.opportunity.previousStage,resultStage:manifest.demoContent.opportunity.resultStage,resultInterviewingCount:1,actionVisible:true,contact:manifest.demoContent.contact,opportunity:manifest.demoContent.opportunity,message:manifest.demoContent.message});
  const banned=auditV11BannedStrings(manifest.demoContent.message.body,manifest.demoContent.disclosure);
  const layout=manifest.scenes.map(({id,layout})=>({sceneId:id,...auditV11Layout(layout)}));
  const fingerprints:V11CompositionFingerprint[]=manifest.scenes.map((scene)=>({frame:scene.from,product:scene.layout.find(({kind})=>kind==="product")??null,mascot:scene.layout.find(({kind})=>kind==="mascot")??null,background:scene.conceptual?`conceptual-${scene.family}`:"product",cameraScale:scene.camera.scaleTo,semanticState:scene.camera.semanticTarget}));
  const similarity=auditV11CompositionSimilarity(fingerprints);
  const phone=auditV11PhoneScale({requiredTextCoverage:1,primaryFocalPoints:2,contactReadable:true,messageReadable:true,mascotFaceReadable:true,captionCollisionCount:0,evidencePixelsArePrimary:false});
  const sourceIds=new Set(manifest.sources.map(({id})=>id),),missingSources=(["tracker_before","tracker_after","opportunity","contact","outreach_blank","outreach_complete"] as V11AssetId[]).filter((id)=>!sourceIds.has(id));
  const passed=narration===manifest.script&&words>=112&&words<=122&&wpm>=185&&wpm<=205&&semantic.every(({passed:ok})=>ok)&&transitions.passed&&mascot.passed&&hook.passed&&cta.passed&&captionLints.passed&&numeralAnchors.passed&&bounds.passed&&story.passed&&banned.passed&&layout.every(({passed:ok})=>ok)&&similarity.passed&&phone.passed&&missingSources.length===0;
  return{passed,narrationExact:narration===manifest.script,words,wpm,semantic,transitions,mascot,hook,cta,captionLints,numeralAnchors,bounds,story,banned,layout,similarity,phone,missingSources};
}

export function assertSolomonCreatorStoryV11Manifest(manifest:SolomonCreatorStoryV11Manifest){
  z.object({schemaVersion:z.literal("11"),id:z.literal(SOLOMON_CREATOR_STORY_V11_ID),sources:z.array(z.unknown()).length(6),claims:z.array(z.unknown()).min(6),scenes:z.array(z.unknown()).length(17),captions:z.array(z.unknown()).min(8)}).parse(manifest);
  manifest.scenes.forEach((scene,index)=>{if(scene.from!==(index?manifest.scenes[index-1]!.to:0)||scene.to<=scene.from)throw new Error(`V11 scene ${scene.id} is not contiguous.`);v11MascotPerformanceSchema.parse(scene.mascot);});
  if(manifest.scenes.at(-1)?.to!==1080)throw new Error("V11 timeline must end at frame 1080.");
  const audit=auditSolomonCreatorStoryV11(manifest);if(!audit.passed)throw new Error(`V11 contract failed: ${JSON.stringify(audit)}`);
}

function claim(id:string,clause:string,assetIds:V11AssetId[],requiredReadableText:string[],actionFrame:number,resultFrame:number):V11Claim{return{id,clause,assetIds,requiredReadableText,actionFrame,resultFrame,approved:true};}
function scene(id:string,from:number,to:number,narration:string,family:V11Family,assetIds:V11AssetId[],claimIds:string[],mascotPlan:V11MascotPerformance,transition:V11Scene["transition"]["type"],proofRecipe:string,typography:V11Scene["typography"],conceptual:boolean,layout:V11Rect[],camera:V11Scene["camera"]):V11Scene{return{id,from,to,narration,family,assetIds,claimIds,mascot:mascotPlan,semanticEvents:events(from,to,id),transition:{type:transition,purpose:`Advance ${id} through ${proofRecipe}`},layout,camera,proofRecipe,typography,conceptual};}
function events(from:number,to:number,id:string):V11SemanticEvent[]{const result=[];for(let frame=from;frame<to;frame+=18)result.push({frame,kind:"semantic" as const,description:`${id} semantic state ${result.length+1}`});return result;}
function mascot(sceneId:string,duration:number,role:V11MascotPerformance["role"],face:V11Face,mouthBias:V11Mouth,leftGesture:V11Gesture,rightGesture:V11Gesture,target:"camera"|"product"|"caption"|"cta",elementId:string,purpose:V11MascotPerformance["narrativePurpose"],faceAccents?:V11MascotPerformance["faceAccents"]):V11MascotPerformance{const absent=role==="absent";return v11MascotPerformanceSchema.parse({sceneId,role,narrativePurpose:purpose,face,mouthBias,faceAccents,gazePath:absent?[{frame:0,target:"camera",x:.5,y:.4}]:[{frame:0,target:"camera",x:.5,y:.4},{frame:3,target,x:target==="cta"?.72:target==="product"?.68:.5,y:target==="cta"?.68:.42}],head:{turn:target==="product"?.42:target==="cta"?.3:0,tilt:sceneId.length%2?.12:-.1,beats:[4,Math.max(8,Math.floor(duration*.55))]},torso:{lean:(faceAccents??[]).some(({face:accent})=>accent==="surprised")?.58:face==="concerned"?-.38:.25,rotate:sceneId.length%2?.12:-.1,recoil:face==="concerned"?.55:.12},left:{gesture:leftGesture,timing:{start:5,peak:Math.min(duration-8,Math.max(11,Math.floor(duration*.32))),recover:Math.min(duration-2,Math.max(18,Math.floor(duration*.74))),wristRotation:14}},right:{gesture:rightGesture,timing:{start:8,peak:Math.min(duration-5,Math.max(16,Math.floor(duration*.48))),recover:Math.min(duration-1,Math.max(22,Math.floor(duration*.86))),wristRotation:-18}},blinkFrames:[Math.max(10,Math.floor(duration*.43)),Math.max(14,Math.floor(duration*.43)+2)],audioFrames:Array.from({length:duration},(_,frame)=>({frame,rms:frame%7===0?.16:.42,speaking:!absent,onset:frame%17===3?.7:.06,phraseBoundary:frame%29===0})),interactionTarget:absent?undefined:{elementId,x:target==="cta"?.72:.68,y:target==="cta"?.68:.42,action:`${leftGesture}/${rightGesture}`}});}
function layouts(mode:"hero"|"host"|"left"|"right"|"product"):V11Rect[]{const caption:V11Rect={id:"caption",kind:"caption",left:.05,top:.04,right:.95,bottom:.16};if(mode==="hero"||mode==="host")return[{id:"mascot",kind:"mascot",left:.18,top:.18,right:.82,bottom:.78},caption];if(mode==="product")return[{id:"product",kind:"product",left:.06,top:.18,right:.94,bottom:.78},caption];return mode==="left"?[{id:"mascot",kind:"mascot",left:.02,top:.7,right:.32,bottom:.98},{id:"product",kind:"product",left:.38,top:.18,right:.96,bottom:.68},caption]:[{id:"mascot",kind:"mascot",left:.68,top:.7,right:.98,bottom:.98},{id:"product",kind:"product",left:.04,top:.18,right:.62,bottom:.68},caption];}
