import { Audio, Video } from "@remotion/media";
import { AbsoluteFill, Sequence, interpolate, spring, staticFile, useCurrentFrame, useVideoConfig } from "remotion";
import { V11_CAMERA_ENVELOPE } from "../../shared/creatorStoryV11Quality";
import { SOLOMON_CREATOR_STORY_V11_HEADLINES, type SolomonCreatorStoryV11Manifest, type V11AssetId, type V11Caption, type V11Scene } from "../../shared/solomonCreatorStoryV11";
import { MascotLayer } from "./MascotLayer";

const SerifHeadline:React.FC<{sceneId:string;accentColor:string;fontSize:number;top:number;left?:number;right?:number;align?:"left"|"center"}> = ({sceneId,accentColor,fontSize,top,left=70,right=70,align="center"}) => {
  const headline=SOLOMON_CREATOR_STORY_V11_HEADLINES[sceneId];
  if(!headline)return null;
  return <div data-v11-headline={sceneId} style={{position:"absolute",left,right,top,fontFamily:"Fraunces Variable,serif",fontSize,lineHeight:.94,fontWeight:850,textAlign:align}}>{headline.primary}{headline.accentItalic&&<><br/><i style={{color:accentColor}}>{headline.accentItalic}</i></>}</div>;
};

const INK="#07111f", PAPER="#fbf8f0", WHITE="#fff", MINT="#39f2b5", GREEN="#087052", CORAL="#ff6f61", AMBER="#ff9d18";
const FILES:Record<V11AssetId,string>={tracker_before:"proof-tracker-before.mp4",tracker_after:"proof-tracker-after.mp4",opportunity:"proof-opportunity.mp4",contact:"proof-contact.mp4",outreach_blank:"proof-outreach-blank.mp4",outreach_complete:"proof-outreach-complete.mp4"};
type Crop={x:number;y:number;width:number;height:number;trim:number};
const CROPS={
  trackerBefore:{x:72,y:178,width:560,height:310,trim:145},trackerAfter:{x:258,y:178,width:560,height:310,trim:155},trackerControl:{x:940,y:285,width:430,height:390,trim:105},
  opportunityHeader:{x:72,y:75,width:760,height:265,trim:52},opportunityPanel:{x:75,y:95,width:900,height:520,trim:142},
  contactCard:{x:86,y:510,width:430,height:390,trim:130},contactProof:{x:104,y:610,width:390,height:265,trim:140},
  outreachBlank:{x:82,y:175,width:520,height:590,trim:85},message:{x:594,y:185,width:755,height:560,trim:180},messageDraftEdit:{x:594,y:185,width:755,height:560,trim:75},messageEdit:{x:594,y:185,width:755,height:560,trim:20}
} satisfies Record<string,Crop>;

export const SolomonCreatorStoryV11:React.FC<SolomonCreatorStoryV11Manifest> = (manifest) => <AbsoluteFill style={{background:INK,color:INK,fontFamily:"Manrope Variable,Manrope,sans-serif",overflow:"hidden"}}>
  {manifest.scenes.map((scene)=><Sequence key={scene.id} from={scene.from} durationInFrames={scene.to-scene.from} premountFor={30} name={scene.id}><Scene scene={scene}/></Sequence>)}
  <MascotLayer scenes={manifest.scenes}/>
  {manifest.captions.map((caption)=><Sequence key={caption.id} from={caption.from} durationInFrames={caption.to-caption.from} premountFor={10}><Caption caption={caption}/></Sequence>)}
  <Sequence from={42} durationInFrames={897}><Disclosure/></Sequence>
  <Audio src={staticFile("narration.wav")}/><Audio src={staticFile("sound-design.wav")}/>
</AbsoluteFill>;

const Scene:React.FC<{scene:V11Scene}> = ({scene}) => <EditorialCamera scene={scene}><SceneContent scene={scene}/></EditorialCamera>;

const SceneContent:React.FC<{scene:V11Scene}> = ({scene}) => {
  if(scene.family==="hook")return <Hook scene={scene}/>;
  if(scene.family==="status")return <Status scene={scene}/>;
  if(scene.family==="contact")return <Contact scene={scene} reasons={false}/>;
  if(scene.family==="reasons"&&scene.id==="reasons")return <Contact scene={scene} reasons/>;
  if(scene.family==="friction")return <Friction scene={scene}/>;
  if(scene.family==="five_surfaces")return <FiveSurfaces scene={scene}/>;
  if(scene.family==="collapse")return <Collapse scene={scene}/>;
  if(scene.family==="role")return <Role scene={scene}/>;
  if(scene.family==="reasons")return <Reason scene={scene}/>;
  if(scene.family==="signature")return <Signature scene={scene}/>;
  if(scene.family==="draft")return <Draft scene={scene}/>;
  if(scene.family==="grounded")return <Grounded scene={scene}/>;
  if(scene.family==="control")return <Control scene={scene}/>;
  if(scene.family==="payoff")return <Payoff scene={scene}/>;
  if(scene.family==="result")return <Result scene={scene}/>;
  if(scene.family==="cta")return <Cta scene={scene}/>;
  return <Sting scene={scene}/>;
};

const Hook:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),flash=interpolate(frame,[0,5,12,20],[.2,1,.55,.15]);return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 28%,#e9fff7,#a9ded0 62%,#72bcaa)"}}><div style={{position:"absolute",inset:0,background:`radial-gradient(circle at 50% 38%,rgba(57,242,181,${flash*.24}),transparent 48%)`}}/><SerifHeadline sceneId="hook" accentColor={GREEN} fontSize={69} top={1430}/></AbsoluteFill>;};

const Status:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),swap=frame>=10,p=spring({frame:Math.max(0,frame-8),fps:30,config:{damping:14,stiffness:210},durationInFrames:8});return <EvidenceBackground><div style={{position:"absolute",left:70,right:70,top:265,height:600}}><EvidenceCard><EvidenceCrop asset={swap?"tracker_after":"tracker_before"} crop={swap?CROPS.trackerAfter:CROPS.trackerBefore} width={940} height={600}/></EvidenceCard></div><div style={{position:"absolute",left:120,right:120,top:920,display:"flex",alignItems:"center",justifyContent:"center",gap:22,fontSize:34,fontWeight:950}}><StatePill text="APPLIED" active={!swap}/><span style={{fontSize:54,color:GREEN}}>→</span><StatePill text="INTERVIEWING" active={swap}/></div><Cursor frame={frame} from={{x:875,y:980}} to={{x:727,y:1005}} clickAt={9}/>{swap&&<div style={{position:"absolute",left:680,top:445,width:180,height:180,borderRadius:999,border:`8px solid ${MINT}`,opacity:1-p,transform:`scale(${.4+p*1.4})`}}/>}</EvidenceBackground>;};

const Contact:React.FC<{scene:V11Scene;reasons:boolean}> = ({scene,reasons}) => {const frame=useCurrentFrame(),card=spring({frame,fps:30,config:{damping:16,stiffness:180},durationInFrames:8});return <EvidenceBackground accent={reasons?"#dff9f0":"#eef8f4"}><div style={{position:"absolute",left:reasons?55:340,top:reasons?280:300,width:reasons?970:680,height:reasons?760:810,transform:`translateX(${(1-card)*(reasons?-100:140)}px) scale(${.86+.14*card})`}}><EvidenceCard><EvidenceCrop asset="contact" crop={reasons?CROPS.contactProof:CROPS.contactCard} width={reasons?970:680} height={reasons?760:810}/></EvidenceCard></div>{reasons?<ReasonStack frame={frame}/>:<div style={{position:"absolute",left:350,right:55,top:1160,display:"grid",gap:13}}><ProofLabel text="AVERY CHEN" primary/><ProofLabel text="SENIOR TECHNICAL RECRUITER"/><ProofLabel text="NORTHSTAR LABS"/></div>}</EvidenceBackground>;};

const Friction:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame();return <AbsoluteFill style={{background:"linear-gradient(145deg,#fff4ee,#ffd9d0)"}}><SerifHeadline sceneId="friction" accentColor={CORAL} fontSize={82} top={120} left={58} right={58} align="left"/>{["JOB","PROFILE","NOTES","CONTACT","EMAIL"].map((label,index)=><div key={label} style={{position:"absolute",left:65+(index%2)*460,top:500+Math.floor(index/2)*250,width:420,height:205,padding:26,borderRadius:27,background:WHITE,border:"2px solid #efc4bb",boxShadow:"0 22px 50px rgba(103,44,32,.15)",transform:`translate(${interpolate(frame,[0,10+index*2],[index%2?-430:430,0],{extrapolateRight:"clamp"})}px,${Math.sin((frame+index*7)/8)*5}px) rotate(${index%2?-3:3}deg)`}}><div style={{fontSize:22,fontWeight:950,color:CORAL}}>0{index+1}</div><div style={{fontSize:36,fontWeight:950,marginTop:22}}>{label}</div><div style={{height:10,width:`${52+index*7}%`,background:"#f1ddd8",borderRadius:8,marginTop:24}}/></div>)}</AbsoluteFill>;};

const FiveSurfaces:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),copy=interpolate(frame,[28,70],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});const cards=[{label:"JOB POST",asset:"opportunity" as const,crop:CROPS.opportunityHeader},{label:"PROFILE",asset:"contact" as const,crop:CROPS.contactCard},{label:"NOTES",asset:"opportunity" as const,crop:CROPS.opportunityPanel},{label:"CONTACTS",asset:"contact" as const,crop:CROPS.contactProof},{label:"BLANK MESSAGE",asset:"outreach_blank" as const,crop:CROPS.outreachBlank}];return <AbsoluteFill style={{background:"linear-gradient(145deg,#fff7ef,#ffe0d6)"}}><div style={{position:"absolute",left:55,top:105,fontFamily:"Fraunces Variable,serif",fontSize:170,fontWeight:900,color:CORAL,lineHeight:.75}}>5×</div><SerifHeadline sceneId="five" accentColor={CORAL} fontSize={49} top={130} left={315} right={55} align="left"/>{cards.map((item,index)=>{const x=52+(index%2)*490,y=390+Math.floor(index/2)*320,enter=spring({frame:Math.max(0,frame-index*7),fps:30,config:{damping:16,stiffness:170},durationInFrames:8});return <div key={item.label} style={{position:"absolute",left:x,top:y,width:450,height:260,borderRadius:25,overflow:"hidden",background:WHITE,border:"2px solid #e8b8ae",boxShadow:"0 20px 45px rgba(103,44,32,.14)",opacity:enter,transform:`scale(${.78+.22*enter})`}}><EvidenceCrop asset={item.asset} crop={item.crop} width={450} height={260}/><div style={{position:"absolute",left:13,bottom:13,padding:"9px 13px",borderRadius:11,background:INK,color:WHITE,fontSize:19,fontWeight:950}}>{item.label}</div></div>})}<div style={{position:"absolute",left:265,top:1170,width:550,height:90,borderRadius:22,background:WHITE,border:`4px solid ${CORAL}`,display:"grid",placeItems:"center",fontSize:28,fontWeight:950,opacity:copy,transform:`translateY(${(1-copy)*80}px)`}}>PRODUCT ENGINEER · NORTHSTAR LABS</div></AbsoluteFill>;};

const Collapse:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),p=spring({frame,fps:30,config:{damping:16,stiffness:160},durationInFrames:8});return <EvidenceBackground>{[0,1,2,3,4].map((index)=>{const angle=index*Math.PI*2/5-Math.PI/2,x=390+Math.cos(angle)*330*(1-p),y=690+Math.sin(angle)*460*(1-p);return <div key={index} style={{position:"absolute",left:x,top:y,width:300,height:170,background:WHITE,border:"2px solid #c8d7d0",borderRadius:18,opacity:1-p*.78,transform:`scale(${1-p*.45}) rotate(${index*4-8}deg)`}}/>})}<div style={{position:"absolute",left:145,top:555,width:790,height:470,opacity:p,transform:`scale(${.65+.35*p})`}}><EvidenceCard border={GREEN}><EvidenceCrop asset="opportunity" crop={CROPS.opportunityHeader} width={790} height={470}/></EvidenceCard></div><SerifHeadline sceneId="collapse" accentColor={GREEN} fontSize={55} top={1080} left={220} right={220}/></EvidenceBackground>;};

const Role:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame();return <EvidenceBackground><div style={{position:"absolute",left:55,top:300,width:700,height:620}}><EvidenceCard><EvidenceCrop asset="opportunity" crop={CROPS.opportunityHeader} width={700} height={620}/></EvidenceCard></div><div style={{position:"absolute",left:80,top:970,width:620,display:"grid",gap:15}}><ProofLabel text="PRODUCT ENGINEER" primary/><ProofLabel text="NORTHSTAR LABS"/></div><Connector frame={frame} from={{x:410,y:930}} to={{x:410,y:970}}/></EvidenceBackground>;};

const Reason:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame();return <EvidenceBackground><div style={{position:"absolute",left:340,top:280,width:690,height:780}}><EvidenceCard><EvidenceCrop asset="contact" crop={CROPS.contactCard} width={690} height={780}/></EvidenceCard></div><div style={{position:"absolute",left:350,right:55,top:1100,display:"grid",gap:12}}>{["WORKS AT NORTHSTAR LABS","RELEVANT RECRUITING ROLE","SUPPORTING EVIDENCE INCLUDED"].map((text,index)=><ProofLabel key={text} text={text} primary={index===0} delay={index*7} frame={frame}/>)}</div></EvidenceBackground>;};

const Signature:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),phase=Math.min(3,Math.floor(frame/28)),travel=(frame%28)/28;const tokens=[{label:"JOB",x:65,asset:"opportunity" as const,crop:CROPS.opportunityHeader},{label:"PERSON",x:315,asset:"contact" as const,crop:CROPS.contactCard},{label:"PROOF",x:565,asset:"contact" as const,crop:CROPS.contactProof},{label:"MESSAGE",x:815,asset:"outreach_complete" as const,crop:CROPS.message}];return <AbsoluteFill style={{background:"linear-gradient(145deg,#ddfff4,#dceff7)"}}><SerifHeadline sceneId="signature" accentColor={GREEN} fontSize={67} top={125} left={55} right={55}/><svg width="1080" height="1920" style={{position:"absolute",inset:0}}><path d="M145 1160 C330 1020 745 1020 935 1160" fill="none" stroke={GREEN} strokeWidth="10" strokeLinecap="round" strokeDasharray="18 17"/></svg>{tokens.map((token,index)=>{const active=index<=phase,enter=spring({frame:Math.max(0,frame-index*26),fps:30,config:{damping:16,stiffness:170},durationInFrames:8});return <div key={token.label} style={{position:"absolute",left:token.x,top:720,width:200,height:300,borderRadius:24,overflow:"hidden",background:WHITE,border:`4px solid ${active?GREEN:"#b9cbc4"}`,boxShadow:"0 20px 45px rgba(7,17,31,.15)",opacity:.25+.75*enter,transform:`translateY(${(1-enter)*80}px) scale(${.75+.25*enter})`}}><EvidenceCrop asset={token.asset} crop={token.crop} width={200} height={300}/><div style={{position:"absolute",left:10,right:10,bottom:10,padding:"10px 5px",borderRadius:11,background:index===3?MINT:INK,color:index===3?INK:WHITE,textAlign:"center",fontSize:20,fontWeight:950}}>{token.label}</div></div>})}{phase<3&&<div style={{position:"absolute",left:tokens[phase]!.x+160+(tokens[phase+1]!.x-tokens[phase]!.x-40)*travel,top:1100-Math.sin(travel*Math.PI)*85,width:42,height:42,borderRadius:999,background:MINT,boxShadow:"0 0 24px rgba(57,242,181,.9)"}}/>}</AbsoluteFill>;};

const Draft:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),complete=frame>=18,p=spring({frame:Math.max(0,frame-14),fps:30,config:{damping:16,stiffness:180},durationInFrames:8});return <EvidenceBackground><div style={{position:"absolute",left:55,top:310,width:970,height:850}}><EvidenceCard border={complete?GREEN:undefined}><EvidenceCrop asset={complete?"outreach_complete":"outreach_blank"} crop={complete?CROPS.messageDraftEdit:CROPS.outreachBlank} width={970} height={850}/></EvidenceCard></div>{complete&&<><div style={{position:"absolute",left:94,top:995,width:870,height:16,borderRadius:9,background:MINT,opacity:.85*p,transform:`scaleX(${p})`,transformOrigin:"left"}}/><div style={{position:"absolute",left:95,top:1185,padding:"13px 19px",borderRadius:14,background:MINT,color:INK,fontSize:29,fontWeight:950,opacity:p}}>SAVE EDIT · DRAFT NOT SENT</div></>}</EvidenceBackground>;};

// The grounded beat introduces a new idea (generic → grounded), so its boundary
// is a real cut: the card arrives with a fast slide rather than morphing
// continuously out of the draft scene, which is what the declared match_cut says.
const Grounded:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),reveal=interpolate(frame,[10,55],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),arrive=spring({frame,fps:30,config:{damping:18,stiffness:220},durationInFrames:7});return <EvidenceBackground accent="#e6f6ee"><div style={{position:"absolute",left:55,top:300,width:970,height:820,transform:`translateX(${(1-arrive)*640}px)`}}><EvidenceCard border={GREEN}><EvidenceCrop asset="outreach_complete" crop={CROPS.message} width={970} height={820}/><div style={{position:"absolute",left:67,top:328,width:760*reveal,height:72,borderRadius:12,background:"rgba(57,242,181,.24)",borderBottom:`7px solid ${MINT}`}}/></EvidenceCard></div><div style={{position:"absolute",left:80,right:80,top:1175,display:"flex",gap:18,alignItems:"center",justifyContent:"center",fontSize:29,fontWeight:950}}><span style={{padding:"14px 18px",borderRadius:14,background:"#ffe2dc",color:CORAL,textDecoration:"line-through"}}>GENERIC OPENER</span><span style={{fontSize:52}}>→</span><span style={{padding:"14px 18px",borderRadius:14,background:MINT}}>ROLE + RELEVANCE</span></div></EvidenceBackground>;};

const Control:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame();return <EvidenceBackground><div style={{position:"absolute",left:330,top:275,width:700,height:830}}><EvidenceCard border={GREEN}><EvidenceCrop asset="outreach_complete" crop={CROPS.messageEdit} width={700} height={830} playback/></EvidenceCard></div><div style={{position:"absolute",left:350,right:55,top:1145,display:"grid",gap:12}}><ProofLabel text="SAVE EDIT" primary/><ProofLabel text="CANCEL · SEND UNTOUCHED"/><div style={{padding:"16px 20px",borderRadius:15,background:MINT,color:INK,fontSize:27,fontWeight:950}}>NOTHING SENDS WITHOUT YOU</div></div><Cursor frame={frame} from={{x:890,y:1040}} to={{x:660,y:985}} clickAt={78}/></EvidenceBackground>;};

const Payoff:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),collapse=interpolate(frame,[0,42],[0,1],{extrapolateRight:"clamp"}),result=spring({frame:Math.max(0,frame-35),fps:30,config:{damping:15,stiffness:155},durationInFrames:8});const windows=[{asset:"tracker_after" as const,crop:CROPS.trackerAfter,x:30,y:330},{asset:"opportunity" as const,crop:CROPS.opportunityHeader,x:560,y:300},{asset:"contact" as const,crop:CROPS.contactCard,x:65,y:870},{asset:"outreach_complete" as const,crop:CROPS.message,x:565,y:850},{asset:"outreach_blank" as const,crop:CROPS.outreachBlank,x:310,y:1230}];return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 40%,#e7fff7,#acdccc)"}}>{windows.map((item,index)=><div key={index} style={{position:"absolute",left:item.x+(390-item.x)*collapse,top:item.y+(610-item.y)*collapse,width:480,height:300,borderRadius:23,overflow:"hidden",background:WHITE,border:"2px solid #b9cbc4",opacity:1-collapse,transform:`scale(${1-collapse*.55}) rotate(${index%2?-4:4}deg)`}}><EvidenceCrop asset={item.asset} crop={item.crop} width={480} height={300}/></div>)}<div data-v11-connected-result style={{position:"absolute",left:42,top:285,width:996,height:1010,borderRadius:36,background:WHITE,border:`7px solid ${GREEN}`,boxShadow:"0 32px 90px rgba(7,17,31,.22)",opacity:result,transform:`scale(${.7+.3*result})`,overflow:"hidden"}}><ConnectedBoard frame={frame}/></div><div style={{opacity:result}}><SerifHeadline sceneId="payoff" accentColor={GREEN} fontSize={72} top={1350}/></div></AbsoluteFill>;};

const Result:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),pulse=1+Math.sin(frame/9)*.012;return <EvidenceBackground accent="#d5f8ec"><div data-v11-connected-result style={{position:"absolute",left:45,top:260,width:990,height:1000,borderRadius:36,background:WHITE,border:`7px solid ${GREEN}`,boxShadow:"0 32px 90px rgba(7,17,31,.22)",transform:`scale(${pulse})`,overflow:"hidden"}}><ConnectedBoard frame={frame+80}/></div><SerifHeadline sceneId="result" accentColor={GREEN} fontSize={67} top={1325}/></EvidenceBackground>;};

const ConnectedBoard:React.FC<{frame:number}> = ({frame}) => <div style={{position:"absolute",inset:0,padding:32,display:"grid",gridTemplateRows:"170px 275px 1fr",gap:18,background:"linear-gradient(145deg,#fff,#f2fbf7)"}}><div style={{position:"relative",overflow:"hidden",borderRadius:22,border:`3px solid ${GREEN}`}}><EvidenceCrop asset="tracker_after" crop={CROPS.trackerAfter} width={932} height={170}/><div style={{position:"absolute",left:14,bottom:12,padding:"9px 14px",borderRadius:11,background:INK,color:WHITE,fontSize:22,fontWeight:950}}>PRODUCT ENGINEER · INTERVIEWING</div></div><div style={{display:"grid",gridTemplateColumns:".9fr 1.1fr",gap:16}}><div style={{position:"relative",overflow:"hidden",borderRadius:22,border:"2px solid #c9d8d1"}}><EvidenceCrop asset="contact" crop={CROPS.contactCard} width={410} height={275}/><div style={{position:"absolute",left:12,bottom:12,padding:"8px 12px",borderRadius:10,background:INK,color:WHITE,fontSize:18,fontWeight:950}}>AVERY CHEN</div></div><div style={{position:"relative",overflow:"hidden",borderRadius:22,border:"2px solid #c9d8d1"}}><EvidenceCrop asset="contact" crop={CROPS.contactProof} width={506} height={275}/><div style={{position:"absolute",right:12,bottom:12,padding:"8px 12px",borderRadius:10,background:MINT,color:INK,fontSize:18,fontWeight:950}}>SUPPORTING EVIDENCE</div></div></div><div style={{position:"relative",overflow:"hidden",borderRadius:22,border:"2px solid #c9d8d1"}}><EvidenceCrop asset="outreach_complete" crop={CROPS.message} width={932} height={497}/><div style={{position:"absolute",left:14,bottom:14,display:"flex",gap:9}}><span style={{padding:"9px 14px",borderRadius:10,background:GREEN,color:WHITE,fontSize:18,fontWeight:950}}>EDITABLE · UNSENT</span><span style={{padding:"9px 14px",borderRadius:10,background:WHITE,border:"2px solid #c9d8d1",fontSize:18,fontWeight:900}}>Save Edit · Cancel</span></div><div style={{position:"absolute",right:14,bottom:22,fontSize:18,fontWeight:850,color:GREEN,opacity:interpolate(frame,[40,55],[0,1],{extrapolateRight:"clamp"})}}>Nothing sends automatically</div></div><div style={{position:"absolute",right:44,top:9,fontSize:12,fontWeight:900,letterSpacing:2,color:GREEN}}>CONCEPTUAL ASSEMBLY · APPROVED PRODUCT EVIDENCE</div></div>;

const Cta:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),type=spring({frame:Math.max(0,frame-38),fps:30,config:{damping:14,stiffness:190},durationInFrames:8}),dim=interpolate(frame,[0,26],[0,.42],{extrapolateRight:"clamp"}),pulse=frame>=58?1+Math.sin((frame-58)/4)*.05*Math.max(0,1-(frame-58)/48):1;return <AbsoluteFill style={{background:"radial-gradient(circle at 50% 32%,#e8fff7,#a8ddce)"}}><div style={{position:"absolute",inset:0,background:`rgba(7,17,31,${dim})`}}/><SerifHeadline sceneId="cta" accentColor={MINT} fontSize={76} top={230}/><div style={{position:"absolute",left:365,right:365,top:470,padding:"10px 14px",borderRadius:999,background:INK,color:WHITE,textAlign:"center",fontSize:23,fontWeight:900,letterSpacing:2}}>@SOLOMON</div><div data-v11-comment-box style={{position:"absolute",left:120,right:120,top:1190,transform:`scale(${pulse})`}}><div style={{padding:"22px 28px",borderRadius:24,background:"rgba(255,255,255,.94)",border:`4px solid ${MINT}`,boxShadow:`0 0 ${34+type*46}px rgba(57,242,181,${.2+.35*type})`,display:"flex",alignItems:"center",gap:16}}><div style={{width:52,height:52,borderRadius:999,background:INK,display:"grid",placeItems:"center",color:MINT,fontSize:26,fontWeight:950}}>S</div><div style={{fontSize:38,fontWeight:950,letterSpacing:1,color:INK}}>{"SOLOMON".slice(0,Math.max(1,Math.round(type*7)))}<span style={{opacity:.35}}>|</span></div></div><div style={{marginTop:14,textAlign:"center",fontSize:24,fontWeight:900,color:WHITE,opacity:.92}}>COMMENT AND THE DEMO ARRIVES IN YOUR DMS</div></div></AbsoluteFill>;};

const Sting:React.FC<{scene:V11Scene}> = ({scene}) => {const frame=useCurrentFrame(),p=spring({frame,fps:30,config:{damping:15,stiffness:175},durationInFrames:8});return <AbsoluteFill style={{background:INK,display:"grid",placeItems:"center"}}><div style={{fontFamily:"Fraunces Variable,serif",fontSize:120,fontWeight:900,color:WHITE,transform:`scale(${.8+.2*p})`,opacity:p}}>{(SOLOMON_CREATOR_STORY_V11_HEADLINES["sting"]?.primary??"SOLOMON.").replace(/\.$/,"")}<span style={{color:AMBER}}>.</span></div></AbsoluteFill>;};

const EvidenceCrop:React.FC<{asset:V11AssetId;crop:Crop;width:number;height:number;playback?:boolean}> = ({asset,crop,width,height,playback=false}) => {const frame=useCurrentFrame(),scale=Math.max(width/crop.width,height/crop.height),videoWidth=1440*scale,videoHeight=900*scale,panX=Math.sin(frame/13)*4,panY=Math.cos(frame/17)*3,focusScale=1.02+Math.sin(frame/21)*.003;return <div data-v11-product={asset} style={{position:"absolute",inset:0,overflow:"hidden",background:WHITE}}><Video src={staticFile(FILES[asset])} trimBefore={crop.trim} muted playbackRate={playback?1:0.35} style={{position:"absolute",left:-crop.x*scale,top:-crop.y*scale,width:videoWidth,height:videoHeight,maxWidth:"none",transform:`translate(${panX}px,${panY}px) scale(${focusScale})`,transformOrigin:`${(crop.x+crop.width/2)/14.4}% ${(crop.y+crop.height/2)/9}%`}}/></div>;};
const EvidenceCard:React.FC<React.PropsWithChildren<{border?:string}>> = ({children,border}) => <div style={{position:"absolute",inset:0,overflow:"hidden",borderRadius:32,background:WHITE,border:`${border?5:2}px solid ${border??"rgba(7,17,31,.12)"}`,boxShadow:"0 28px 70px rgba(7,17,31,.18)"}}>{children}</div>;
const EvidenceBackground:React.FC<React.PropsWithChildren<{accent?:string}>> = ({children,accent="#f5f8f4"}) => <AbsoluteFill style={{background:`linear-gradient(145deg,${PAPER},${accent})`}}>{children}</AbsoluteFill>;
// Camera stays inside V11_CAMERA_ENVELOPE so no layout rect can cross the frame
// edge, and "calm" scenes (reading moments) damp the sway to near zero for their
// middle stretch, which is what restores the reference-style calm frames.
const EditorialCamera:React.FC<React.PropsWithChildren<{scene:V11Scene}>> = ({scene,children}) => {
  const frame=useCurrentFrame(),duration=Math.max(1,scene.to-scene.from-1);
  const progress=interpolate(frame,[0,duration],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});
  const declaredTravel=Math.max(0,scene.camera.scaleTo-scene.camera.scaleFrom);
  const baseScale=V11_CAMERA_ENVELOPE.baseScaleMax,push=progress*Math.min(V11_CAMERA_ENVELOPE.pushMax,declaredTravel*.1);
  const calm=isCalmScene(scene);
  const calmDamp=calm?(progress>.2&&progress<.8?.2:.55):1;
  const swayX=Math.sin((frame+scene.from*.13)/13)*V11_CAMERA_ENVELOPE.swayXMax*calmDamp;
  const swayY=Math.cos((frame+scene.from*.17)/17)*V11_CAMERA_ENVELOPE.swayYMax*calmDamp;
  const focusX=(scene.camera.focus.x-.5)*-V11_CAMERA_ENVELOPE.focusShiftMax,focusY=(scene.camera.focus.y-.5)*-V11_CAMERA_ENVELOPE.focusShiftMax;
  const heldPush=calm&&progress>.2&&progress<.8?progress*0+.2*Math.min(V11_CAMERA_ENVELOPE.pushMax,declaredTravel*.1):push;
  return <AbsoluteFill data-v11-camera={scene.camera.recipe} data-v11-calm={calm?"true":"false"} style={{transform:`translate(${swayX+focusX*progress}px,${swayY+focusY*progress}px) scale(${baseScale+heldPush})`,transformOrigin:`${scene.camera.focus.x*100}% ${scene.camera.focus.y*100}%`}}>{children}</AbsoluteFill>;
};
function isCalmScene(scene:V11Scene){return scene.typography==="product_annotation";}
const Disclosure=()=> <div data-v11-disclosure style={{position:"absolute",left:26,top:26,zIndex:80,padding:"6px 10px",borderRadius:8,background:"rgba(255,255,255,.84)",border:"1px solid rgba(7,112,82,.25)",color:GREEN,fontSize:14,fontWeight:900,letterSpacing:2}}>DEMO DATA</div>;
const StatePill:React.FC<{text:string;active:boolean}> = ({text,active}) => <div style={{padding:"18px 25px",borderRadius:18,background:active?GREEN:WHITE,color:active?WHITE:INK,border:`3px solid ${active?GREEN:"#c9d8d1"}`,boxShadow:active?"0 12px 30px rgba(7,112,82,.22)":"none"}}>{text}</div>;
const ProofLabel:React.FC<{text:string;primary?:boolean;delay?:number;frame?:number}> = ({text,primary=false,delay=0,frame=30}) => {const p=spring({frame:Math.max(0,frame-delay),fps:30,config:{damping:16,stiffness:190},durationInFrames:8});return <div style={{padding:"15px 20px",borderRadius:15,background:primary?INK:WHITE,color:primary?WHITE:INK,border:`2px solid ${primary?INK:"#c9d8d1"}`,fontSize:25,fontWeight:950,opacity:p,transform:`translateX(${(1-p)*45}px)`}}>{text}</div>;};
const ReasonStack:React.FC<{frame:number}> = ({frame}) => <div style={{position:"absolute",left:90,right:90,top:1100,display:"grid",gap:13}}>{["WORKS AT NORTHSTAR LABS","RELEVANT RECRUITING ROLE","SUPPORTING EVIDENCE INCLUDED"].map((text,index)=><ProofLabel key={text} text={text} primary={index===0} delay={index*7} frame={frame}/>)}</div>;
const Cursor:React.FC<{frame:number;from:{x:number;y:number};to:{x:number;y:number};clickAt:number}> = ({frame,from,to,clickAt}) => {const p=interpolate(frame,[0,Math.max(1,clickAt-2)],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"}),click=interpolate(frame,[clickAt-1,clickAt,clickAt+4],[1,.8,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <svg viewBox="0 0 40 52" width="56" height="73" style={{position:"absolute",left:from.x+(to.x-from.x)*p,top:from.y+(to.y-from.y)*p,zIndex:60,transform:`scale(${click})`,filter:"drop-shadow(0 4px 4px rgba(0,0,0,.42))"}}><path d="M4 3 L4 39 L14 30 L22 48 L30 44 L22 27 L36 27 Z" fill="#fff" stroke="#111827" strokeWidth="3"/></svg>;};
const Connector:React.FC<{frame:number;from:{x:number;y:number};to:{x:number;y:number}}> = ({frame,from,to}) => {const p=interpolate(frame,[4,25],[0,1],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});return <svg width="1080" height="1920" style={{position:"absolute",inset:0}}><path d={`M${from.x} ${from.y} Q${(from.x+to.x)/2+70} ${(from.y+to.y)/2} ${to.x} ${to.y}`} fill="none" stroke={MINT} strokeWidth="9" strokeLinecap="round" pathLength="1" strokeDasharray="1" strokeDashoffset={1-p}/></svg>;};

const Caption:React.FC<{caption:V11Caption}> = ({caption}) => {const frame=useCurrentFrame(),{durationInFrames}=useVideoConfig(),enter=spring({frame,fps:30,config:{damping:17,stiffness:185},durationInFrames:9}),opacity=interpolate(frame,[Math.max(0,durationInFrames-4),durationInFrames],[1,0],{extrapolateLeft:"clamp",extrapolateRight:"clamp"});
  const text=caption.beatText;
  const highlightIndex=caption.highlight?text.toLowerCase().indexOf(caption.highlight.toLowerCase()):-1;
  const pre=highlightIndex>=0?text.slice(0,highlightIndex):text;
  const highlighted=highlightIndex>=0?text.slice(highlightIndex,highlightIndex+(caption.highlight?.length??0)):undefined;
  const post=highlightIndex>=0?text.slice(highlightIndex+(caption.highlight?.length??0)):"";
  return <div data-v11-caption={caption.id} style={{position:"absolute",left:45,right:45,[caption.zone==="top"?"top":"bottom"]:caption.zone==="top"?82:92,display:"flex",justifyContent:"center",zIndex:70,opacity,transform:`translateY(${(1-enter)*(caption.zone==="top"?-25:25)}px)`}}><div style={{padding:"12px 18px",borderRadius:14,background:"rgba(7,17,31,.91)",color:WHITE,fontSize:37,lineHeight:1.06,textAlign:"center",fontWeight:950,boxShadow:"0 12px 30px rgba(0,0,0,.18)"}}>{pre}{highlighted&&<span style={{color:MINT}}>{highlighted}</span>}{post}</div></div>;};
